stytchauth/stytch-ios

- .spi.yml
It is my understanding that this custom scheme should fix [this issue](https://swiftpackageindex.com/builds/005703F8-F4FB-4FE4-AFF8-FDF54E3622FC), per [this blog post](https://blog.swiftpackageindex.com/posts/the-swift-package-index-metadata-file-first-steps/)
> [build] Add custom scheme name for SPI manifest

- Package.swift
- README.md
- Resources/Sourcery/Templates/AsyncVariants.stencil
- Sources/StytchCore/Generated/StytchClient+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.MagicLinks+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.MagicLinks.Email+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.OneTimePasscodes+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.Sessions+AsyncVariants.generated.swift
- Sources/StytchCore/KeychainClient/KeychainClient.swift
- Sources/StytchCore/SessionStorage.swift
- Stytch.podspec
- Tests/StytchCoreTests/AsyncMethodsTestCase.swift
To reduce the complexity for various upcoming features and the associated security concerns, and to reduce overall complexity as it pertains to ongoing internal maintenance, we have decided to update our minimum deployment target to iOS 13. Among other things this will allow us to base the internal async mechanisms off of Swift's modern Async/Await concurrency systems. We will, however, still provide Combine and Completion-handler hooks for external consumption.
Based on our analysis, as of last month, iOS users on versions < iOS 13.0 made up roughly 5% of total iOS users worldwide. Given this SDK is a net-new product, we are choosing to begin its lifetime without the technical debt of managing older OS versions. We will, in the near future, create a formal policy for supported iOS …
> [build] Update min deployment target to iOS 13

- Sources/StytchCore/KeychainClient/KeychainClient+Live.swift
- Sources/StytchCore/KeychainClient/KeychainClient.swift
- Sources/StytchCore/KeychainClient/KeychainMigration.swift
- Sources/StytchCore/KeychainClient/Migrations/Migration1.swift
- Sources/StytchCore/SessionStorage.swift
- Sources/StytchCore/StytchClient/StytchClient+Environment.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Tests/StytchCoreTests/KeychainClientTestCase.swift
For consistency with upcoming keychain items, we are migrating all items to use kSecAttrService instead of kSecAttrAccount as the key corresponding to the KeychainClient.Item name property. This PR makes that change and introduces keychain migrations to accomodate this, and future, changes.
> [refactor] Add keychain migrations

- Sources/StytchCore/KeychainClient/KeychainClient+Live.swift
- Sources/StytchCore/KeychainClient/KeychainClient.swift
- Sources/StytchCore/SessionStorage.swift
- Sources/StytchCore/StytchClient/Sessions/StytchClient+PKCE.swift
- Tests/StytchCoreTests/BaseTestCase.swift
- Tests/StytchCoreTests/KeychainClientTestCase.swift
Refactors KeychainClient to take in a new ItemData struct when setting an item, but maintains string convenience methods. This sets us up to a) return multiple results for biometrics keys and b) to pass in and return additional metadata for a given keychain query result
> [refactor] Adjust KeychainClient to return array of results

- .github/workflows/release.yml
- .github/workflows/test.yml
- .swiftlint.yml
- Package.swift
- Scripts/current-version
- Sources/StytchCore/ClientInfo/ClientInfo+SDK.swift
- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
- Stytch.podspec
- Bump version to 0.3.0
- Add current_version script
- Remove redundant docc-plugin dep to fix release workflow
- Add checks in workflow that versioning matches tag name
> [version] bump version & provide better checks for tag <-> version checks

- .github/workflows/test.yml
- Gemfile
- Scripts/demo
* Add `dotenv` to Gemfile
* Only require dotenv when loading env so `setup` can be called before dotenv is installed
[Linear ticket](https://linear.app/stytch/issue/SDK-657/%5Bios-sdk-demo%5D-missing-dotenv-gem-after-running-make-demo)
> [fix] Fix dotenv Script/demo dependency

- Sources/StytchCore/StytchClient/OAuth/OAuth+ThirdParty.swift
- Sources/StytchCore/StytchClient/OAuth/StytchClient+OAuth.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
add enum/interfaces for new oauth providers
Note none of them were added to `StytchDemo/Client/Shared/OAuthAuthenticationView.swift`, so to consider there
Completes SDK-690
> austin/oauth: add figma, snpachat, tiktok, twitter

- .github/actions/bootstrap/action.yml
- .github/workflows/cut_version.yml
- .github/workflows/docs.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Brewfile.lock.json
- Makefile
- Extracts `Bootstrap` commands to reusable action
- Parallelizes test execution on all platforms
- Runs watchOS tests only when there is a `test-watchos` label or when tests are run on the main branch
> [platform] Improve ci execution time

- .github/workflows/release.yml
- Makefile
- Fixes missing arch error encountered in [recent workflow run](https://github.com/stytchauth/stytch-swift/actions/runs/3841410579/jobs/6541595097) by moving command to Makefile and having ARCH be dynamic
- Completes SDK-740 by using gh cli vs action-gh-release
> [platform] Fix and improve release workflow

- Sources/StytchCore/Generated/StytchClient.MagicLinks.Email.loginOrCreate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.MagicLinks.Email.send+AsyncVariants.generated.swift
- Sources/StytchCore/StytchClient/MagicLinks/Email/Email.swift
- Sources/StytchCore/StytchClient/OneTimePasscodes/OneTimePasscodes.swift
- Sources/StytchCore/StytchClient/Passwords/Passwords.swift
- StytchDemo/Client/Shared/EmailAuthenticationView.swift
- StytchDemo/Client/Shared/HobbiesView.swift
- StytchDemo/Client/Shared/OTPAuthenticationView.swift
- StytchDemo/Client/Shared/Passwords/PasswordAuthenticationView.swift
- StytchDemo/Client/Shared/Passwords/PasswordModel.swift
- Tests/StytchCoreTests/MagicLinksTestCase.swift
- Tests/StytchCoreTests/NetworkingClientInterceptor.swift
- Tests/StytchCoreTests/OneTimePasscodesTestCase.swift
- Tests/StytchCoreTests/PasskeysTestCase.swift
- Tests/StytchCoreTests/PasswordsTestCase.swift
* Adding in template id values to params
* Consolidation of param types where possible
* Some test cleanup
* Adding the ability to adjust template ids in the demo app
Completes SDK-788
> [feat] Add custom email template support

- .github/workflows/docs.yml
- Makefile
- README.md
As part of the current docs overhaul, this PR adds support so that documentation is generated for each tagged version, as well as for the main branch and for the latest tag, so the docs for a given version will be available at `https://stytchauth.github.io/stytch-swift/<ref>/documentation/stytchcore/` with ref being any of the tag values as well as `main` or `latest`. I've gone ahead and manually pushed up docs for each of these so we could be sure it would work properly, several examples of which you can see at:
- https://stytchauth.github.io/stytch-swift/latest/documentation/stytchcore/
- https://stytchauth.github.io/stytch-swift/main/documentation/stytchcore/
- https://stytchauth.github.io/stytch-swift/0.1.0/documentation/stytchcore/
- …
> feat: Add support for versioned docs

- .github/workflows/docs.yml
> fix: Use github context sha when when not in git repo

- Sources/StytchCore/Environment.swift
- Sources/StytchCore/KeychainClient/KeychainClient+Item.swift
- Sources/StytchCore/StytchClientCommon/StytchClientType.swift
- Tests/StytchCoreTests/KeychainClientTestCase.swift
Due to default iOS behavior of persisting Keychain items/data when an app is uninstalled, our SDK will maintain session data even after an app is uninstalled/reinstalled. This is generally undesirable, and potentially a security concern, so we will start resetting the Keychain when we determine an app is freshly installed. We will do this by leveraging UserDefaults, which do get cleared between installs where we will store a Stytch Install ID. When this value is nil, we know we should clear the keychain
> [improvement] Reset Keychain on fresh app install

- Sources/StytchCore/StytchClient/OAuth/OAuth+Apple.swift
- StytchDemo/Client/Shared/OAuthAuthenticationView.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
Consumes a new user_created field from web-backend, which informs the client whether Sign In With Apple auth is for a new or returning user
Completes client work for SDK-870
> [feat] Add ability to tell if user new/returning for SIWA

- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
Why did this fail when building the archive, but not fail the tests? It is a mystery!
> Fix import

- Sources/StytchCore/ClientType.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SSO.swift
- Sources/StytchCore/StytchClient/OAuth/OAuth+ThirdParty.swift
- Sources/StytchCore/WebAuthenticationSessionClient/WebAuthenticationSessionClient+Live.swift
- Sources/StytchCore/WebAuthenticationSessionClient/WebAuthenticationSessionClient.swift
Not sure if this is the Swiftiest way to accomplish this (tried to pass in the instance of the StytchClientType, but ran into compilation issues), but this works in the Workbench app.
> SDK-1093 Conditionally use either consumer or B2B client in WebAuthenticationSessionClient

- .github/workflows/publish.yml
Use correct credentials to allow publishing to S3.
> [TECH-481] Use prod_cdn updater credentials in publish CI

- .gitignore
- Package.swift
- Sources/StytchCore/DFPClient/DFPClient+live.swift
- Sources/StytchCore/DFPClient/DFPClient.swift
- Sources/StytchCore/DFPClient/dfp.html
- Sources/StytchCore/Environment.swift
- Sources/StytchCore/NetworkingClient/NetworkingClient+Live.swift
- Sources/StytchCore/StytchClientCommon/StytchClientType.swift
- StytchDemo/Client/Shared/StytchConfiguration.plist
- StytchDemo/StytchDemo.xcodeproj/xcshareddata/xcschemes/StytchDemo (iOS).xcscheme
Linear Ticket: [SDK-1133](https://linear.app/stytch/issue/SDK-1129)
Doing this a little bit out of order, but this is functionality for injecting the webview and awaiting the telemetry ID
> DFP: Inject webview and fetch telemetry ID

- Sources/StytchCore/NetworkingClient/NetworkingClient+Live.swift
Linear Ticket: [SDK-1134](https://linear.app/stytch/issue/SDK-1134)
- If DFP is enabled, inject dfp_telemetry_id
- If DFP is enabled and response is 403, inject dfp_telemetry_id and captcha_token and rerun the request
> DFP: Inject telemetry ID and captcha token as necessary

- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Bootstrap.swift
- Sources/StytchCore/StytchClient/Bootstrap/StytchClient+Bootstrap.swift
- Sources/StytchCore/StytchClientCommon/Models/BootstrapResponse.swift
With the changes to WB, siteKey is not guaranteed to be returned if CAPTCHA is not configured. This was breaking the marshalling of the response to a BoostrapResponse type, so we were not configuring DFP even when it was turned on.
> Fix issue when siteKey doesnt exist

- Sources/StytchCore/Generated/StytchClient.Passwords.resetBySession+AsyncVariants.generated.swift
- Sources/StytchCore/StytchClient/Passwords/PasswordsRoute.swift
- Sources/StytchCore/StytchClient/Passwords/StytchClient+Passwords.swift
- Tests/StytchCoreTests/PasswordsTestCase.swift
Linear Ticket: [SDK-1174](https://linear.app/stytch/issue/SDK-1174)
1. Adds PasswordResetBySession endpoint
-
> SDK-1174 password reset by session

- Sources/StytchCore/StytchClientCommon/Models/StytchError.swift
- Tests/StytchCoreTests/B2BMagicLinksTestCase.swift
- Tests/StytchCoreTests/B2BPasswordsTestCase.swift
- Tests/StytchCoreTests/B2BSSOTestCase.swift
- Tests/StytchCoreTests/DeeplinkHandlerTestCase.swift
- Tests/StytchCoreTests/MagicLinksTestCase.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
- Tests/StytchCoreTests/PasswordsTestCase.swift
- Tests/StytchCoreTests/SessionsTestCase.swift
- Tests/StytchCoreTests/XCTestHelpers.swift
Linear Ticket: [SDK-1315](https://linear.app/stytch/issue/SDK-1315)
1. Updated `XCTAssertThrowsErrorAsync` function to include a StytchError param
2. Updated unit tests using the `XCTAssertThrowsErrorAsync` function to check for specific errors
-
> Update tests to use specific errors

- Sources/StytchUI/AuthRootViewController.swift
- Sources/StytchUI/StytchUIClient.swift
- StytchDemo/Client/Shared/AuthenticationOptionsView.swift
Linear Ticket: [SDK-1298](https://linear.app/stytch/issue/SDK-1298)
- Adds an `onAuthCallback` param that allows a callback with `AuthenticateResponse` after successful authentication
-
> [SDK-1298] Auth Response Callback

- Sources/StytchCore/DeeplinkHandledStatus.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Sources/StytchUI/PasswordViewModel.swift
- Sources/StytchUI/StytchUIClient.swift
- StytchDemo/Client/Shared/AuthenticationOptionsView.swift
Linear Ticket: [SDK-1299](https://linear.app/stytch/issue/SDK-1299)
- fixes UI displaying for redirected password reset flow
- calls `onAuthCallback` after any deeplink handled response
-
> Fix password reset UI

- Sources/StytchUI/AuthInputViewController.swift
- Sources/StytchUI/Inputs/CodeInput.swift
- Sources/StytchUI/Inputs/PhoneNumberInput.swift
- Sources/StytchUI/OTPCodeViewController.swift
- StytchDemo/StytchDemo.xcodeproj/project.pbxproj
- StytchDemo/StytchUIDemo/ContentView.swift
- StytchDemo/StytchUIDemo/StytchUIDemo.entitlements
- StytchDemo/StytchUIDemo/StytchUIDemoApp.swift
- StytchDemo/StytchUITests/StytchUILaunchTests.swift
- StytchDemo/StytchUITests/StytchUITests.swift
Linear Ticket: [SDK-1361](https://linear.app/stytch/issue/SDK-1361)
1. Adds basic test for the OTP confirmation screen
- The phone number we're using is a Twilio test number
> SDK-1361 UI Test OTP screen

- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Events.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Routes.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/Events/StytchClient+Events.swift
- Sources/StytchCore/StytchClient/OAuth/StytchClient+OAuth.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Sources/StytchCore/StytchClientCommon/StytchClientType.swift
- Sources/StytchUI/AuthHomeViewModel.swift
- Sources/StytchUI/OAuthViewController.swift
- Sources/StytchUI/OTPCodeViewController.swift
- Sources/StytchUI/PasswordViewController.swift
- Sources/StytchUI/StytchUIClient.swift
- StytchDemo/Client/Shared/StytchConfiguration.plist
- Tests/StytchCoreTests/NetworkingClientInterceptor.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
Linear Ticket: [SDK-1401](https://linear.app/stytch/issue/SDK-1401)
1. Fixes the name of the render_login_screen event (underscores, not dashes)
2. Adds event support to B2B client
3. Adds _most_ of the desired events
- The one event that is missing is `client_initialization_failure`, because I can't figure out a way to catch that
- I spent a good few hours trying to figure out how to get the details for the `render_login_screen` event to send as JSON instead of a string (something I just fixed in Android), but can't figure that out, either. I think it's fine for now, the important thing is really the event firing
> SDK-1401 quick win metrics

- Sources/StytchCore/StytchClient/Models/User.swift
Linear Ticket: [SDK-1414](https://linear.app/stytch/issue/SDK-1414)
1. Adds profilePictureUrl to Provider struct
- Tested in demo app with GitHub login
> SDK-1414 Add profile_picture_url to Provider struct

- Package.swift
- Sources/StytchCore/NetworkingClient/NetworkingClient+Live.swift
- StytchDemo/StytchDemo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Linear Ticket: [SDK-1449](https://linear.app/stytch/issue/SDK-1449)
1. Bumps Google reCAPTCHA version due to a new vulnerability
2. Fixes a bug when sending events with DFP enabled (the fix is to _not_ try to append DFP/CAPTCHA tokens to events)
-
> SDK-1449 Bump reCAPTCHA

- Sources/StytchCore/Generated/StytchClient.Passwords.resetByExistingPassword+AsyncVariants.generated.swift
- Sources/StytchCore/StytchClient/Passwords/PasswordsRoute.swift
- Sources/StytchCore/StytchClient/Passwords/StytchClient+Passwords.swift
- Tests/StytchCoreTests/PasswordsTestCase.swift
- Tests/StytchUIUnitTests/Spies.swift
Linear Ticket: [SDK-1470](https://linear.app/stytch/issue/SDK-1470)
- Adds `resetByExistingPassword` method to `StytchClient.passwords`
-
> Add resetByExistingPassword to B2C Passwords client

- Sources/StytchCore/Environment.swift
- Sources/StytchCore/Routing/NetworkingRouter.swift
- Sources/StytchCore/SessionStorage.swift
- Sources/StytchCore/StytchClient/Models/User.swift
- Sources/StytchCore/StytchClient/User/StytchClient+User.swift
- Sources/StytchCore/StytchClient/User/UsersRoute.swift
- Sources/StytchCore/UserStorage.swift
- Tests/StytchCoreTests/UserManagementTestCase.swift
Linear Ticket: [SDK-1471](https://linear.app/stytch/issue/SDK-1471)
Adds the following methods to the user management client:
- `onChange`
- `deleteFactor` for TOTP and OAuth registrations
-
> Update iOS User headless client

- Sources/StytchCore/Generated/StytchClient.CryptoWallets.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.CryptoWallets.authenticateStart+AsyncVariants.generated.swift
- Sources/StytchCore/Routing/BaseRoute.swift
- Sources/StytchCore/StytchClient/CryptoWallets/CryptoWalletsRoute.swift
- Sources/StytchCore/StytchClient/CryptoWallets/StytchClient+CryptoWallets.swift
- Tests/StytchCoreTests/CryptoWalletsTestCase.swift
Linear Ticket: [SDK-1469](https://linear.app/stytch/issue/SDK-1469)
Adds `stytch.cryptoWallets` with the following methods:
- `authenticateStart`
- `authenticate`
-
> iOS B2C Crypto Wallets client

- Sources/StytchCore/AppleOAuthClient/AppleOAuthClient+Live.swift
- Sources/StytchCore/AppleOAuthClient/AppleOAuthClient.swift
- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
- Sources/StytchCore/StytchClient/OAuth/OAuth+Apple.swift
- Sources/StytchCore/StytchClient/OAuth/StytchClient+OAuth.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
Linear Ticket: [SDK-1482](https://linear.app/stytch/issue/SDK-1482)
1. Mimic the fix from RN, where we explicitly make a user update request IF we get a name back from Apple
-
> SDK-1482 Attempt to fix Sign In With Apple name issues

- Package.swift
Fixes #209
1. Restrict number kit to minor version of 3.5. Versions above this break build.  
- Previous would allow number kit to bump to 3.7 which had a breaking change per 
- [x ] I have verified that this change works in the relevant demo app, or N/A
> Restric version of numberkit

- Sources/StytchCore/StytchClient/OAuth/OAuth+Apple.swift
Linear Ticket: [SDK-1535](https://linear.app/stytch/issue/SDK-1535)
1. We were expecting a UserResponse from updating new users, but were instead receiving a nested user response. Since we don't use/care about the response, we can just expect a BasicResponse
-
> Fix expected response from SIWA update user request

- Sources/StytchCore/Extensions/Dictionary+Stytch.swift
- Sources/StytchCore/KeychainClient/KeychainClient+Item.swift
`kSecAttrAccessible` and `kSecAttrAccessControl` are [mutually exclusive](https://developer.apple.com/documentation/security/ksecattraccesscontrol). The first attribute is used to make a keychain item available after the first unlock (which we use so session tokens are available during fetches when the app is backgrounded) and the second one we use to specify that something can only be accessed with a biometric. Seems obvious in hindsight that they wouldn't work together!
Linear Ticket: [SDK-1561](https://linear.app/stytch/issue/SDK-1561)
1. If both `kSecAttrAccessible` and `kSecAttrAccessControl` are requested for the same keychain item, disregard the `kSecAttrAccessible` attribute, preferring `kSecAttrAccessControl`
-
> SDK-1561 Fix issue with Biometrics registration

- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Bootstrap.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SSO.swift
- Sources/StytchCore/StytchClient/Bootstrap/StytchClient+Bootstrap.swift
- Sources/StytchCore/StytchClient/OAuth/OAuth+ThirdParty.swift
Linear Ticket: [SDK-1589](https://linear.app/stytch/issue/SDK-1589)
1. Persist bootstrap data
2. Use cname if available for oauth and sso
> SDK-1589 Enable CNAME domains for OAuth and SSO

- Sources/StytchCore/DFPClient/DFPClient.swift
Linear Ticket: [LINEAR_NUMBER](https://linear.app/stytch/issue/YOUR_TICKET)
1. Inject the webview into the _root_ viewcontroller, instead of the topmost
2. make sure that we _remove_ the webview after completing the flow
- Validated in workbench
> SDK-1670 Fix race condition when DFP is enabled and there is a disappearing viewcontroller

- Sources/StytchCore/StytchClientCommon/Models/Response.swift
I wanted to expose the `let wrapped: Wrapped` value inside `public struct Response<Wrapped: Decodable>: Decodable`. There is already a way to access individual fields of the response using the subscript `public subscript<T>(dynamicMember member: KeyPath<Wrapped, T>) -> T` but this makes it easier if you would like a reference to the whole object without needing to access the fields piecemeal.
> Expose wrapped value in Response

- Sources/StytchCore/Environment.swift
- Sources/StytchCore/Generated/StytchB2BClient.Members.deleteFactor+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.Members.update+AsyncVariants.generated.swift
- Sources/StytchCore/MemberStorage.swift
- Sources/StytchCore/StytchB2BClient/Models/Member.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Members.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Routes.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/MemberViewController.swift
- Tests/StytchCoreTests/B2BMagicLinksTestCase.swift
- Tests/StytchCoreTests/B2BMembersTestCase.swift
Linear Ticket: Add methods for b2b member client: [SDK-1474](https://linear.app/stytch/issue/SDK-1474)
- onChange
- update
- deleteFactor (deleteMFAPhoneNumber, deletePassword, deleteMFATOTP)
- Much of these changes parodied the way we implemented `User` and `StytchClient+User`.
1. Create `MemberStorage` to cache the current member.
2. Add `memberPasswordId` property to the member object to help with the delete password factor flow.
3. Add `onMemberChange` publisher to `StytchB2BClient+Members` so we can be notified when changes to the member happen.
4. Add `func update(...)` to `StytchB2BClient+Members` so we can update the current member.
5. Add `func deleteFactor(...)` to `StytchB2BClient+Members` for phone number, totp and password.
6. Unify member response with `MemberResponseData` …
> [SDK-1474][B2B] Add methods for b2b member client

- Sources/StytchCore/Generated/Sessions.exchange+AsyncVariants.generated.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Sessions.swift
- Sources/StytchCore/StytchClientCommon/Sessions/SessionsRoute.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/DiscoveryViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/MagicLinksViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/PasswordsViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/SSOViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/SessionsViewController.swift
- StytchDemo/B2BWorkbench/RootViewController.swift
- StytchDemo/B2BWorkbench/SceneDelegate.swift
- Tests/StytchCoreTests/B2BSessionsTestCase.swift
Linear Ticket: [SDK-1473: Add exchange method to session client](https://linear.app/stytch/issue/SDK-1473/[ios]-[b2b]-add-method-for-session-client)
- The session exchange function works if there is a user that is authenticated by email magic links or oauth and is a member of multiple organizations. You can then call the session exchange function with the id of the org they wish to authenticate with and it will create and return a new member session.
1. Extend `Sessions` to include an `exchnage` method. And add the `ExchangeParameters` type.
2. In the b2b sample app remove all usage of a defined property for `private let defaults: UserDefaults = .standard` and instead refer directly to `UserDefaults.standard`. I feel that this is confusing and would imply custom usage of user default and …
> [SDK-1473][B2B] Add exchange method to session client

- Sources/StytchCore/Generated/StytchB2BClientSessions.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClientSessions.exchange+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClientSessions.revoke+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClientSessions.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClientSessions.revoke+AsyncVariants.generated.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Routes.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Sessions.swift
- Sources/StytchCore/StytchClient/StytchClient+Sessions.swift
- Sources/StytchCore/StytchClientCommon/Sessions/Sessions.swift
- Sources/StytchCore/StytchClientCommon/Sessions/SessionsRoute.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/SessionsViewController.swift
- Tests/StytchCoreTests/B2BSessionsTestCase.swift
- Tests/StytchCoreTests/SessionsTestCase.swift
Linear Ticket: [SDK-1733](https://linear.app/stytch/issue/SDK-1733/[ios][b2b]-create-separate-session-clients-for-b2b-and-b2c)
1. Remove the generics usage of the `Sessions` object and split into 2 separate objects. `StytchClientSessions` and `StytchB2BClientSessions`.
2. @jhaven-stytch and I had decided to do this after the [pr for adding the exchange method](https://github.com/stytchauth/stytch-ios/pull/233) to the b2b client and that he had already done this on Android. 
3. We felt that this was better so that the exchange method was not available for usage on the b2c client which it had been previously and that any additional changes that needed to be scoped for the session object on either b2c or b2b remained in their respective sandbox.
4. All functionality not needed to make public …
> [SDK-1733] Create separate session clients for B2B and B2C.

- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
We check the validity of a persisted session on `StytchClient`/`StytchB2BClient` initialization (and on 3 minute interval while foregrounded), but it's possible for a session to expire/be revoked while the app is backgrounded, and an authentication call immediately following foregrounding would fail with an `Unauthorized credentials` error.
This adds an observer to force check a user's persisted session on app foregrounding to avoid this issue.
> Refresh session on app foregrounding

- Sources/StytchCore/PollingClient/PollingClient+Live.swift
Noticed that the polling client for the member sessions "heartbeat" was using the wrong client
> Member session polling client should use B2B sessions authenticate

- Sources/StytchCore/Generated/StytchB2BClient.SearchManager.searchMember+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.SearchManager.searchOrganization+AsyncVariants.generated.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Common.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Organizations/StytchB2BClient+Organizations+UpdateParameters.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Routes.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SSO/StytchB2BClient+SSO+OIDC.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SSO/StytchB2BClient+SSO+SAML.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SearchManager.swift
- StytchDemo/B2BWorkbench/AuthHomeViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/DiscoveryViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/MagicLinksViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/OrganizationViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/PasswordsViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/SearchManagerViewController.swift
- StytchDemo/B2BWorkbench/Extensions.swift
- StytchDemo/StytchDemo.xcodeproj/project.pbxproj
- Tests/StytchCoreTests/B2BSearchManagerTestCase.swift
Linear Ticket: [SDK-1549](https://linear.app/stytch/issue/SDK-1549/[ios]-[b2b]-add-searchorganizationsearchmember-functionality)
1.  Create `StytchB2BClient.SearchManager`.
2.  Add `searchMember` that allows the search for a member of any organization by their email and organization id.
3. Add `searchOrganization` that allows the search for an organization by its slug.
4. In the b2b sample app move the organization id text field to the root screen instead of in each view controller. 
5. Moved some organization code into a common file `StytchB2BClient+Common.swift`
> [SDK-1549] Create SearchManager and add search member and org functions

- Sources/StytchCore/Generated/StytchB2BClient.TOTP.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.TOTP.create+AsyncVariants.generated.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Routes.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+TOTP.swift
- StytchDemo/B2BWorkbench/AuthHomeViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/OrganizationMemberViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/TOTPViewController.swift
- StytchDemo/B2BWorkbench/Extensions.swift
- StytchDemo/StytchDemo.xcodeproj/project.pbxproj
- StytchDemo/StytchDemo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Tests/StytchCoreTests/B2BTOTPTestCase.swift
Linear Ticket: [SDK-1479](https://linear.app/stytch/issue/SDK-1479/[ios]-[b2b]-add-totp-client)
1.  Add `StytchB2BClient+TOTP` and the methods `create` to create a totp secret for the member and `authenticate` to authenticate based on the secret returned.
2. In the sample app add the package `SwiftOTP` which will help generate the code from the secret returned.
> [SDK-1479] Add StytchB2BClient+TOTP

- Sources/StytchCore/Generated/StytchB2BClient.OTP.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.OTP.send+AsyncVariants.generated.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Common.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Routes.swift
- StytchDemo/B2BWorkbench/AuthHomeViewController.swift
- StytchDemo/B2BWorkbench/AuthMethodControllers/OTPViewController.swift
- StytchDemo/StytchDemo.xcodeproj/project.pbxproj
- Tests/StytchCoreTests/B2BOTPTestCase.swift
Linear Ticket: [SDK-1478](https://linear.app/stytch/issue/SDK-1478/[ios]-[b2b]-add-otp-client)
1. Add `StytchB2BClient+OTP` including `send` which will send an opt code via sms, and a `authenticate` with that code.
> [SDK-1478] Add StytchB2BClient+OTP

- Sources/StytchCore/ClientType.swift
- Sources/StytchCore/Domain.swift
- Sources/StytchCore/Environment.swift
- Sources/StytchCore/Extensions/URL+Stytch.swift
- Sources/StytchCore/Generated/StytchB2BClient.OAuth.Discovery.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.OAuth.ThirdParty.Discovery.start+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.OAuth.ThirdParty.start+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.OAuth.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.SSO.start+AsyncVariants.generated.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Events.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+ThirdParty+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+ThirdParty.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Routes.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SSO/StytchB2BClient+SSO.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/WebAuthenticationSessionClient/WebAuthenticationSessionClientConfiguration.swift
- Sources/StytchUI/OAuthViewModel.swift
- StytchDemo/B2BWorkbench/SceneDelegate.swift
- StytchDemo/B2BWorkbench/ViewControllers/AuthHomeViewController.swift
- StytchDemo/B2BWorkbench/ViewControllers/AuthMethodControllers/OAuthViewController.swift
- StytchDemo/B2BWorkbench/ViewControllers/AuthMethodControllers/SSOViewController.swift
- StytchDemo/Client/Shared/OAuthAuthenticationView.swift
- StytchDemo/StytchDemo.xcodeproj/project.pbxproj
- Tests/StytchCoreTests/B2BOAuthTestCase.swift
- Tests/StytchCoreTests/B2BSSOTestCase.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
- Tests/StytchCoreTests/XCTestHelpers.swift
- Tests/StytchUIUnitTests/Spies.swift
Linear Ticket: [SDK-1477](https://linear.app/stytch/issue/SDK-1477/[ios]-[b2b]-add-oauth-client)
1. Create `StytchB2BClient.OAuth` which adds flows for authenticate and discovery authenticate.
2. Also massively refactor any flow that requires authenticating with a web view and centralize all functionality with a newly defined protocol for `WebAuthenticationSessionClientConfiguration`.
4. The `WebAuthenticationSessionClientConfiguration` is able to create an instance of `WebAuthenticationSessionClient.Parameters` which is the object that directs the actual authentication flow.
5. I then refactored B2C OAuth and B2B SSO in addition to adding this new configuration object to the newly created B2B O Auth flows.
> [SDK-1477] Add StytchB2BClient.OAuth

- Sources/StytchCore/StytchClientCommon/Models/SessionToken.swift
- Sources/StytchCore/StytchClientCommon/Sessions/Sessions.swift
- Tests/StytchCoreTests/B2BSessionsTestCase.swift
- Tests/StytchCoreTests/SessionsTestCase.swift
Linear Ticket: [SDK-1726](https://linear.app/stytch/issue/SDK-1726/[ios]-require-non-null-session-token-and-session-jwt-in-updatesession)
1. Create the `SessionTokens` (notice the plural) to enforce updating with both tokens. It is impossible to create this object without one of each token type.
> [SDK-1726]: Require non-null session_token and session_jwt in updateSession

- Package.swift
- StytchDemo/StytchDemo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Linear Ticket: [SDK-1723](https://linear.app/stytch/issue/SDK-1723/[ios]-specify-the-exact-version-number-of-the-dependencies)
1. In the `Package.swift` file we now fix the version of the dependencies using `.exact`.
2. We will now need to manually update the version of the dependencies.
> [SDK-1723] Fix dependencies to an exact version

- Sources/StytchCore/Generated/StytchB2BClient.MagicLinks.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+MagicLinks.swift
- Tests/StytchCoreTests/B2BMagicLinksTestCase.swift
- Tests/StytchCoreTests/MagicLinksTestCase.swift
Linear Ticket: [SDK-1827](https://linear.app/stytch/issue/SDK-1827/[ios]-magic-links-authenticate-should-optionally-use-the-pkce-code)
1.  `b2b/magic_links/authenticate` should use PKCE code challenge if link was created by login or create because the assumption is that its on the same device, but not use the PKCE code challenge if it was sent via the invite endpoint because that would be from a separate device.
> [SDK-1827] Conditionally use PKCE in magic links authenticate

- Sources/StytchCore/Generated/StytchB2BClient.MagicLinks.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.Passwords.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.Passwords.resetByEmail+AsyncVariants.generated.swift
- Sources/StytchCore/KeychainClient/KeychainClient+Item.swift
- Sources/StytchCore/Routing/NetworkingRouter.swift
- Sources/StytchCore/SessionStorage.swift
- Sources/StytchCore/StytchB2BClient/Models/B2BMFAAuthenticateResponse.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+MagicLinks.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Passwords.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Sessions.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+TOTP.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/StytchClient+Sessions.swift
- Sources/StytchCore/StytchClientCommon/IntermediateSessionTokenParameters.swift
- Sources/StytchCore/StytchClientCommon/Models/SessionToken.swift
- StytchDemo/B2BWorkbench/SceneDelegate.swift
- Tests/StytchCoreTests/B2BMagicLinksTestCase.swift
- Tests/StytchCoreTests/B2BPasswordsTestCase.swift
- Tests/StytchCoreTests/B2BSessionsTestCase.swift
- Tests/StytchCoreTests/SessionsTestCase.swift
Linear Ticket: [SDK-1526](https://linear.app/stytch/issue/SDK-1526/[ios]-support-mfa-in-b2b)
This PR adds the first part of B2B MFA and much of the groundwork and plumbing. From here I will need to now add it to all the places that need changes more easily.
1. Add a new response type for the first phase of MFA called `B2BMFAAuthenticateResponse` it has an optional IST and an optional member session.
2. Implement the plumbing for saving a retrieving the IST as well as a new type of parameters for injecting the IST into requests that need it.
3. Change the OTP for to allow for MFA.
4. Refactor `SessionStorage` and change the implementation of `updateSession` to allow for the IST and more flexible use. I considered splitting it up into many functions, but I felt that single function with all …
> [SDK-1526] Add MFA to B2B (Phase 1)

- Sources/StytchCore/Generated/StytchB2BClient.OAuth.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.Passwords.resetByExistingPassword+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.SSO.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClientSessions.exchange+AsyncVariants.generated.swift
- Sources/StytchCore/KeychainClient/KeychainClient.swift
- Sources/StytchCore/SessionStorage.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+MagicLinks.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Passwords.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SSO/StytchB2BClient+SSO.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Sessions.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+TOTP.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClientCommon/IntermediateSessionTokenParameters.swift
- Tests/StytchCoreTests/B2BOAuthTestCase.swift
- Tests/StytchCoreTests/B2BSSOTestCase.swift
- Tests/StytchCoreTests/KeychainClient+Mock.swift
- Tests/StytchCoreTests/SessionStorageTestCase.swift
Linear Ticket: [SDK-1717: Implement 10 minute IST lifespan](https://linear.app/stytch/issue/SDK-1717/[ios]-implement-10-minute-ist-lifespan)
Linear Ticket: [SDK-1832: Support MFA in B2B - All Flows Non Discovery](https://linear.app/stytch/issue/SDK-1832/[ios]-support-mfa-in-b2b-all-flows-non-discovery)
This specific page is super helpful in understanding b2b mfa: https://stytch.com/docs/b2b/guides/mfa/headless
1.  Modify `IntermediateSessionTokenParameters` to take an optional `intermediateSessionToken: String?` and if its nil do not include it, I did this so we don't have to check for its nullability everywhere these parameters are used.
2. Add a 10 minute expiration to the IST stored in the keychain and expose a new method on the `KeychainClient` called `func getQueryResult(_ item: …
> [SDK-1717][SDK-1832] Continue adding MFA to B2B

- Sources/StytchCore/Generated/StytchB2BClient.Discovery.listOrganizations+AsyncVariants.generated.swift
- Sources/StytchCore/Routing/NetworkingRouter.swift
- Sources/StytchCore/SessionStorage.swift
- Sources/StytchCore/StytchB2BClient/Models/B2BMFAAuthenticateResponse.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+MagicLinks.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+Discovery.swift
- Sources/StytchCore/StytchClientCommon/IntermediateSessionTokenParameters.swift
- Sources/StytchCore/StytchClientCommon/Models/Response.swift
- StytchDemo/B2BWorkbench/ViewControllers/AuthMethodControllers/DiscoveryViewController.swift
- Tests/StytchCoreTests/B2BDiscoveryTestCase.swift
- Tests/StytchCoreTests/B2BMagicLinksTestCase.swift
- Tests/StytchCoreTests/B2BOAuthTestCase.swift
- Tests/StytchCoreTests/B2BOTPTestCase.swift
- Tests/StytchCoreTests/B2BPasswordsTestCase.swift
- Tests/StytchCoreTests/B2BSSOTestCase.swift
- Tests/StytchCoreTests/B2BTOTPTestCase.swift
- Tests/StytchCoreTests/BaseTestCase.swift
Linear Ticket: [[SDK-1833] - [iOS] Support MFA in B2B - All Discovery and Discovery OAuth Flows](https://linear.app/stytch/issue/SDK-1833/[ios]-support-mfa-in-b2b-all-discovery-and-discovery-oauth-flows)
1. Modified the discovery flows so that they no longer take an IST in the callers parameters. But instead it is added to the call within the internal implementation.
2. Within `NetworkingRouter` parse out the discovery return types that conform to the newly created `DiscoveryIntermediateSessionTokenDataType` so we can cache the IST separately from the MFA flow.
3. Create a new parameter type `IntermediateSessionTokenParametersWithNoWrappedValue` for when we need to the pass the IST to networking calls that take no other params.
4. Update unit tests to test the internal logic to the public …
> [SDK-1833] Handle the IST for discovery flows

- Sources/StytchCore/StytchB2BClient/StytchB2BClient+DFP.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Sources/StytchUI/ActionableInfoViewModel.swift
- Sources/StytchUI/AuthInputViewModel.swift
- Sources/StytchUI/OTPCodeViewModel.swift
- Sources/StytchUI/PasswordViewModel.swift
Linear Ticket: [[SDK-1574] - [iOS] Mimic event logs from JS SDK](https://linear.app/stytch/issue/SDK-1574/[ios]-mimic-event-logs-from-js-sdk)
1. From my analysis most of the events were already in place.
2. Some were missing in the UI SDK and I added them. 
3. The oauth event names were wrong.
> [SDK-1574] Event Parity

- Sources/StytchCore/Environment.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+MagicLinks.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Passwords.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SSO/StytchB2BClient+SSO.swift
- Sources/StytchCore/StytchClient/MagicLinks/StytchClient+MagicLinks.swift
- Sources/StytchCore/StytchClient/OAuth/StytchClient+OAuth.swift
- Sources/StytchCore/StytchClient/Passwords/StytchClient+Passwords.swift
- Tests/StytchCoreTests/B2BMagicLinksTestCase.swift
- Tests/StytchCoreTests/B2BOAuthTestCase.swift
- Tests/StytchCoreTests/B2BPasswordsTestCase.swift
- Tests/StytchCoreTests/B2BSSOTestCase.swift
- Tests/StytchCoreTests/MagicLinksTestCase.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
- Tests/StytchCoreTests/PasswordsTestCase.swift
Linear Ticket: [[SDK-1826] [iOS] Delete PKCE code after each request](https://linear.app/stytch/issue/SDK-1826/[ios]-delete-pkce-code-after-each-request)
1. When `PKCEPairManager` `generateAndReturnPKCECodePair()` is called it will always be used on the first call in a sequence and `getPKCECodePair()` will be used on the final call in the sequence, therefore every time `getPKCECodePair()` is used from within the SDK we should delete the pair regardless of what the outcome of the call is.
> [SDK-1826] Delete PKCE code after each request

- Sources/StytchCore/Routing/NetworkingRouter.swift
Linear Ticket: [SDK-1883](https://linear.app/stytch/issue/SDK-1883)
1. Delete local biometrics registration if it doesn't exist on the logged in user
The other part of this ticket, only deleting a registration if the network delete succeeds, appears to already be working correctly
> Delete local biometric registration if it doesn't exist on the logged in user

- Sources/StytchCore/Extensions/URL+Stytch.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+ThirdParty+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+ThirdParty.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SSO/StytchB2BClient+SSO.swift
- Sources/StytchCore/StytchClient/OAuth/OAuth+ThirdParty.swift
[Add support for provider_[parameter] parameter](https://linear.app/stytch/issue/SDK-1882/rn-sdk-[maybe-other-mobile-sdks]-add-support-for-provider-[parameter])
1. Update oauth b2c client to add missing param for providerParams.
2. Refactor the way we create the url parameters for the various start urls to remove some awkward code around url parameter generation.
> Add provider params to the B2C OAuth client

- Sources/StytchCore/StytchB2BClient/Models/Member.swift
- Sources/StytchCore/StytchB2BClient/Models/MemberSession.swift
- Sources/StytchCore/StytchB2BClient/Models/Organization.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Bootstrap.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Common.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Members.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+ThirdParty.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Organizations/StytchB2BClient+Organizations+SearchParameters.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Organizations/StytchB2BClient+Organizations.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Passwords.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SSO/StytchB2BClient+SSO.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SearchManager.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Sources/StytchCore/StytchClient/Bootstrap/StytchClient+Bootstrap.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Sources/StytchCore/StytchClientCommon/Models/BootstrapResponse.swift
- Sources/StytchCore/StytchClientCommon/Models/RBACPolicy.swift
- Sources/StytchCore/StytchClientCommon/Models/SessionToken.swift
- Sources/StytchCore/StytchClientCommon/StytchClientType.swift
- Sources/StytchUI/ViewControllers/AuthHomeViewController.swift
[[SDK-1918] Inline documentation audit](https://linear.app/stytch/issue/SDK-1918/[ios]-inline-documentation-audit)
1. Went through all the properties and methods of the SDK and determined which ones needed to be public and which ones could be internal only.
2. Then for all the needed public APIs I made sure they had comments on them.
> [SDK-1918] Inline documentation audit

- Sources/StytchCore/Generated/StytchClient.UserManagement.update+AsyncVariants.generated.swift
- Sources/StytchCore/StytchClient/User/StytchClient+User.swift
- Tests/StytchCoreTests/UserManagementTestCase.swift
Linear Ticket: [[SDK-1724] [iOS] Error when updating user's name](https://linear.app/stytch/issue/SDK-1724/[ios]-error-when-updating-users-name)
1. The update user call had the wrong return type, it was `UserResponse` but it should have been `NestedUserResponse`
> [SDK-1724] Fix user update

- Sources/StytchCore/Documentation.docc/StytchCore.md
- Sources/StytchCore/Generated/StytchB2BClient.Sessions.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.Sessions.exchange+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.Sessions.revoke+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.Sessions.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.Sessions.revoke+AsyncVariants.generated.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Routes.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Sessions.swift
- Sources/StytchCore/StytchClient/StytchClient+Sessions.swift
- Stytch/DemoApps/B2BWorkbench/ViewControllers/AuthMethodControllers/SessionsViewController.swift
- Tests/StytchCoreTests/B2BSessionsTestCase.swift
- Tests/StytchCoreTests/SessionsTestCase.swift
Rename `StytchB2BClient.StytchB2BClientSessions` to `StytchB2BClient.Sessions`.
Rename `StytchClient.StytchClientSessions` to `StytchClient.Sessions`.
Initially `StytchB2BClientSessions` and `StytchClientSessions` were not namespaces because their predecessor, the shared Sessions object was not namespaced. So when I initially split them apart I failed to namespace them and gave them very verbose names, then they were subsequently namespaced and their names became even more verbose. Now we can shorten it for sake of consistency.
> Rename session objects now that they are namespace

- Sources/StytchCore/JSON.swift
- Tests/StytchCoreTests/JSONTestCase.swift
- Tests/StytchCoreTests/XCTestHelpers.swift
Linear Ticket: [[SDK-2085] [iOS] Drop null values from key value pairs in JSON object type](https://linear.app/stytch/issue/SDK-2085/[ios]-drop-null-values-from-key-value-pairs-in-json-object-type)
1. We were having an issue where if the JSON for custom claims had a null value in the key value pair then it would throw an exception. Now that JSON is able to take a key value pair with a null value.
2. It would be worth exploring if we should replace our JSON class with [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON), but that is a greater effort and I feel confident that this will fix the issue.
> [SDK-2085] Allow for optional values in JSON objects

- Sources/StytchCore/Documentation.docc/StytchCore.md
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Sessions.swift
- Sources/StytchCore/StytchClient/StytchClient+Sessions.swift
- Remove the ability to publicly set the session object from the clients.
- Add GitHub repo link to docs.
> Make Sessions Read-Only From Clients

- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+ThirdParty.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
[SDK-2040 - [iOS] Slack B2B OAuth](https://linear.app/stytch/issue/SDK-2040/[ios]-slack-b2b-oauth)
[SDK-2039 - [iOS] Hubspot B2B OAuth](https://linear.app/stytch/issue/SDK-2039/[ios]-hubspot-b2b-oauth)
[SDK-2037 - [iOS] Github B2B OAuth](https://linear.app/stytch/issue/SDK-2037/[ios]-github-b2b-oauth)
1. Expand the `StytchB2BClient.OAuth.ThirdParty.Provider` enum to include the new types.
> Adding New B2B OAuth Providers

- Sources/StytchCore/Generated/StytchB2BClient.Discovery.createOrganization+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.Discovery.exchangeIntermediateSession+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.OAuth.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.OAuth.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.handle+AsyncVariants.generated.swift
- Sources/StytchCore/OAuthProviderValues.swift
- Sources/StytchCore/SharedModels/Response.swift
- Sources/StytchCore/StytchB2BClient/Models/B2BMFAAuthenticateResponse.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/OAuth/StytchClient+OAuth.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Sources/StytchUI/StytchUIClient/StytchUIClient.swift
- Stytch/DemoApps/B2BWorkbench/SceneDelegate.swift
- Stytch/DemoApps/ConsumerWorkbench/Shared/StytchDemoApp.swift
- Stytch/DemoApps/StytchDemo/ContentView.swift
- Stytch/DemoApps/StytchUIDemo/StytchUIDemoApp.swift
- Tests/StytchCoreTests/B2BDiscoveryTestCase.swift
- Tests/StytchCoreTests/B2BMagicLinksTestCase.swift
- Tests/StytchCoreTests/B2BOAuthTestCase.swift
- Tests/StytchCoreTests/B2BPasswordsTestCase.swift
- Tests/StytchCoreTests/B2BSessionsTestCase.swift
- Tests/StytchCoreTests/DeeplinkHandlerTestCase.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
- Tests/StytchUIUnitTests/BaseTestCase.swift
- Tests/StytchUIUnitTests/Spies.swift
- tutorials/Deeplinks.md
[[iOS] Missing fields in B2BMFAAuthenticateResponseData](https://linear.app/stytch/issue/SDK-2078/[ios]-missing-fields-in-b2bmfaauthenticateresponsedata)
[[iOS] Update OAuth Response Types To Include Missing Fields](https://linear.app/stytch/issue/SDK-1992/[ios]-update-oauth-response-types-to-include-missing-fields)
1. Add missing fields to `B2BMFAAuthenticateResponseData`
2. Create `MFARequired` object.
3. Add `OAuthAuthenticateResponseData` for consumer and b2b
4. For b2b add additional cases to the `DeeplinkResponse` for the new oauth response type.
5. For consumer create their own `DeeplinkResponse`.
6. Delete some response types that now were just the standard MFA response type with the expanded types.
> Add missing response types for MFA and OAuth

- Sources/StytchCore/ObjectStorage.swift
- Sources/StytchCore/StytchClientType.swift
[[iOS] Refactor publishing of initial object state](https://linear.app/stytch/issue/SDK-2105/[ios]-refactor-publishing-of-initial-object-state)
1. Rather than force publishing the values of the core object types from outside of `ObjectStorage` make the `publish` method private and have each `ObjectStorage` instance observe the first event in the `StartupClient.isInitialized` publisher and then publish from within the class.
> [SDK-2105] Refactor publishing of initial object state

- Sources/StytchCore/Generated/StytchB2BClient.OTP.Email.Discovery.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.OTP.Email.Discovery.send+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.OTP.Email.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.OTP.Email.loginOrSignup+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.OTP.SMS.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.OTP.SMS.send+AsyncVariants.generated.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Common.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP/StytchB2BClient+OTP+Email+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP/StytchB2BClient+OTP+Email.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP/StytchB2BClient+OTP+SMS.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP/StytchB2BClient+OTP.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Routes.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Stytch/DemoApps/B2BWorkbench/ViewControllers/AuthMethodControllers/OTPViewController.swift
- Tests/StytchCoreTests/B2BOAuthTestCase.swift
- Tests/StytchCoreTests/B2BOTPTestCase.swift
[SDK-2205 - B2B Email OTP](https://linear.app/stytch/issue/SDK-2205/[ios]-b2b-email-otp)
1. I had to refactor the SMS OTP object because I had not properly namespaced it when I initially added it, I had it directly under the OTP struct. Now there is a SMS struct.
2. Added Email and Discovery OTP structs.
3. Moved `DiscoveryAuthenticateResponse` to a common place which is now shared between OAuth and Email for discovery.
> SDK-2205: B2B Email OTP

- Sources/StytchCore/SharedModels/Response.swift
- Sources/StytchCore/StytchB2BClient/Models/B2BMFAAuthenticateResponse.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP/StytchB2BClient+OTP+Email.swift
- Tests/StytchCoreTests/B2BMagicLinksTestCase.swift
- Tests/StytchCoreTests/B2BOAuthTestCase.swift
- Tests/StytchCoreTests/B2BOTPTestCase.swift
1.  Though investigation of functionality of the B2B UI we realized that the MFA response type was missing the needed field "primaryRequired" so we added it.
> Add missing value to MFA response “primaryRequired”

- Sources/StytchUI/StytchB2BUIClient/Shared/BaseViewController+MFA.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/MFAEnrollmentSelectionViewController/MFAEnrollmentSelectionViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/TOTPEnrollmentManualViewController/TOTPEnrollmentViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/TOTPEnrollmentManualViewController/TOTPEnrollmentViewModel.swift
- Stytch/DemoApps/StytchB2BUIDemo/StytchB2BUIDemoApp.swift
1. Modify the TOTP flow to make function where we only load the secret and recovery code when you hit the view controller. And if it fails to load then I change the "Continue" button to say "Try Again" which will attempt to create the TOTP association again. The user can also choose to go back and auth a different way.
> Only load the TOTP Secret when we reach the VC

- Sources/StytchUI/StytchB2BUIClient/Shared/BaseViewController+MFA.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/DiscoveryManager.swift
- Sources/StytchUI/StytchB2BUIClient/StytchB2BUIClient/StytchB2BUIClient.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BOAuthViewController/B2BOAuthViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthRootViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordResetViewController/PasswordResetViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/TOTPEnrollmentManualViewController/TOTPEnrollmentViewController.swift
1. Add a mechanism by which you can use static functions to tell the main `StytchB2BUIClient` to add a loading spinner to its root view controller and remove it. Each asynchronous operation will need to manually call start and stop.
> Add loading Spinner to root VC

- Sources/StytchUI/Components/Button.swift
- Sources/StytchUI/Extensions/UIViewController+StytchUI.swift
- Sources/StytchUI/Shared/StytchTheme.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/AuthenticationOperations.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/B2BAuthenticationManager.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/B2BPasswordsViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/BaseViewController+MFA.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/DiscoveryManager.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/MemberManager.swift
- Sources/StytchUI/StytchB2BUIClient/StytchB2BUIClient/StytchB2BUIClient.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BEmailMagicLinksViewController/B2BEmailMagicLinksViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BOAuthViewController/B2BOAuthViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BSSOViewController/B2BSSOViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BSSOViewController/B2BSSOViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthRootViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/MFAEnrollmentSelectionViewController/MFAEnrollmentSelectionTableViewCell.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/MFAEnrollmentSelectionViewController/MFAEnrollmentSelectionViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/MFAEnrollmentSelectionViewController/MFAMethodSelectionViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/RecoveryCodeEntryViewController/RecoveryCodeEntryViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/RecoveryCodeEntryViewController/RecoveryCodeEntryViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/RecoveryCodeEntryViewController/RecoveryCodeInput.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/RecoveryCodeSaveViewController/RecoveryCodeSaveViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/RecoveryCodeSaveViewController/RecoveryCodesListView.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/TOTPEnrollmentManualViewController/TOTPEnrollmentViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/TOTPEntryViewController/TOTPEntryViewController.swift
[[iOS] Build RecoveryCodeSave](https://linear.app/stytch/issue/SDK-2269/[ios]-build-recoverycodesavel)
1. Modify the logic for when to dismiss the ui, works correctly there are still bugs in the way we present things on SwiftUI. The only flow that is built but not working properly is the recovery codes save screen.
2. The `B2BAuthenticationManager` now has a publisher for `dismissUI` where the logic runs internally.
> [B2B UI] Create publisher to correctly dismiss UI when needed

- Sources/StytchCore/StytchB2BClient/StytchB2BClient+RecoveryCodes.swift
- Tests/StytchCoreTests/B2BRecoveryCodesTestCase.swift
1. We were missing the much needed authentication response types in the recovery code recover endpoint so we added them.
2. Tested it in the B2B workbench app.
> Add authentication fields to recovery code recover

- Sources/StytchUI/Extensions/UILabel+StytchUI.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/AuthenticationOperations.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/BaseViewController+MFA.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/MemberManager.swift
- Sources/StytchUI/StytchB2BUIClient/StytchB2BUIClient/StytchB2BUIClient.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BAuthHomeViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BPasswordsHomeViewController/B2BPasswordsHomeViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/EmailConfirmationViewController/EmailConfirmationViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/EmailConfirmationViewController/EmailConfirmationViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordAuthenticateViewController/PasswordAuthenticateViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordForgotViewController/PasswordForgotViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordForgotViewController/PasswordForgotViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordResetViewController/PasswordResetViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordResetViewController/PasswordResetViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/RecoveryCodeEntryViewController/RecoveryCodeEntryViewModel.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/PasswordViewController/PasswordViewController.swift
- Stytch/DemoApps/B2BWorkbench/ViewControllers/AuthHomeViewController.swift
[[iOS] Build PasswordSetNew](https://linear.app/stytch/issue/SDK-2272/[ios]-build-passwordsetnew)
[[iOS] Build PasswordResetForm](https://linear.app/stytch/issue/SDK-2274/[ios]-build-passwordresetform)
[[iOS] Build PasswordForgotForm](https://linear.app/stytch/issue/SDK-2275/[ios]-build-passwordforgotform)
[[iOS] Build PasswordAuthenticate](https://linear.app/stytch/issue/SDK-2276/[ios]-build-passwordauthenticate)
1. Create centralized and parameterized place by which we show the `EmailConfirmationViewController`.
2. Centralize email and password label creation into one place.
3. Email reset and authentication flow.
4. Move more functionality into view models and out of the global place in `AuthenticationOperations`.
> [B2B UI] Add password screens to B2B UI

- Sources/StytchUI/Shared/OTPEntryViewControllerProtocol.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/AuthenticationOperations.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/MFAEnrollmentSelectionViewController/MFAMethodSelectionViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/SMSOTPEnrollmentViewController/SMSOTPEnrollmentViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/SMSOTPEntryViewController/SMSOTPEntryViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/SMSOTPEntryViewController/SMSOTPEntryViewModel.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/OTPCodeViewController/OTPCodeViewController.swift
[[iOS] Build SMSOTPEnrollment](https://linear.app/stytch/issue/SDK-2268/[ios]-build-smsotpenrollment)
[[iOS] Build SMSOTPEntry](https://linear.app/stytch/issue/SDK-2267/[ios]-build-smsotpentry)
1. Abstract reusable parts of OTP entry into `OTPEntryViewControllerProtocol` that can be shared between B2C and B2B SMS OTP Entry.
2. Complete SMS OTP enrollment and entry flows.
> [B2B UI] SMS OTP Flows

- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+ThirdParty.swift
- Sources/StytchUI/StytchB2BUIClient/StytchB2BUIClient/StytchB2BUIClient+ValidProducts.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BAuthHomeViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BOAuthViewController/B2BOAuthViewController.swift
- Tests/StytchUIUnitTests/StytchB2BUIClientTests/StytchB2BUIClient+HomeScreenProductsTests.swift
- Tests/StytchUIUnitTests/StytchB2BUIClientTests/StytchB2BUIClient+ProductOrderingTests.swift
- Tests/StytchUIUnitTests/StytchB2BUIClientTests/StytchB2BUIClient+ValidProductsTests.swift
1. Add logic so that if the developer specifics `.oauth` as a product they would like to show, but the `B2BOAuthProviderOptions` array does not contain a provider that is in the current org's `AllowedAuthMethods` then we filter it out and potentially even remove `.oauth` from the developer specified products.
2. Add tests for all the product filtering and valid products logic.
> [B2B UI] OAuth Filtering

- Sources/StytchCore/OAuthProviderValues.swift
- Sources/StytchCore/SessionManager.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Common.swift
- Sources/StytchUI/Components/OTPCodeEntryView.swift
- Sources/StytchUI/Inputs/EmailInput.swift
- Sources/StytchUI/Inputs/PhoneNumberInput.swift
- Sources/StytchUI/Inputs/SecureTextInput.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/B2BPasswordsViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/MemberManager.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BAuthHomeViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BEmailMagicLinksViewController/B2BEmailMagicLinksViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BOAuthViewController/B2BOAuthViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BPasswordsHomeViewController/B2BPasswordsHomeViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/ErrorViewController/ErrorViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/MFAEnrollmentSelectionViewController/MFAEnrollmentSelectionViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordAuthenticateViewController/PasswordAuthenticateViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordForgotViewController/PasswordForgotViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordForgotViewController/PasswordForgotViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordResetViewController/PasswordResetViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/RecoveryCodeEntryViewController/RecoveryCodeEntryViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/RecoveryCodeEntryViewController/RecoveryCodeInput.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/RecoveryCodeSaveViewController/RecoveryCodeSaveViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/SMSOTPEnrollmentViewController/SMSOTPEnrollmentViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/SMSOTPEntryViewController/SMSOTPEntryViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/TOTPEnrollmentManualViewController/TOTPSecretView.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/TOTPEntryViewController/TOTPEntryViewController.swift
1. Make `idToken` optional in `OAuthProviderValues` so other OAuth types besides google will not fail in parsing.
2. Modify `OTPCodeEntryView` massively so that we can allow for pasting and a cursor and deleting values.
3. Add keyboard actions wherever needed.
4. Add a formatted phone number to the sms otp entry screen.
5. Hide back button logic. Basically if we already have a MFA response hide the back button, unless we are enrolling in mfa for the first time. Also hide it on the recovery code save screen.
> [B2B UI] Bugbashing

- Sources/StytchUI/Inputs/EmailInput.swift
- Sources/StytchUI/Inputs/PhoneNumberInput.swift
- Sources/StytchUI/Inputs/SecureTextInput.swift
- Sources/StytchUI/Shared/BaseViewController.swift
- Sources/StytchUI/Shared/FontLoader.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthRootViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/RecoveryCodeEntryViewController/RecoveryCodeInput.swift
1. Adds a gesture handler to detect taps outside of the view and autodismisses the keyboard
2. Adds a `resignFirstResponder()` call to the textfield when returning
> Hide keyboard on done/next and tapping outside

- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
1. We determined that if you had previously authenticated with biometrics and then attempted to register a new biometric registration without authenticating with all factors, the attempt to delete a factor would cause a 401 and log the user out thus preventing them from registering the new factor. We deleted that nicety check for now meaning that you can once again register new biometrics registrations leaving the ones in the user object orphaned.
> Dont delete the previous biometric registration

- .github/workflows/test.yml
Linear Ticket: [INFRA-2371](https://linear.app/stytch/issue/INFRA-2371)
1. Removes unused `actions/upload-artifact@v3` step in the `test.yml` workflow. The version used is being phased out and we don't use the uploaded coverage report anywhere
See second commit for changes without editor formatting.
> [part of INFRA-2371] ci: remove unused coverage artifact upload

- Stytch/DemoApps/StytchB2BUIDemo/ContentView.swift
- tutorials/B2B-UI.md
- tutorials/NavigatingTheProject.md
- tutorials/UI.md
1. Add missing redirect types to the ui readmes.
2. Update B2B sample app so that you can hard code the public token and org id in code if you choose.
3. Update the navigating the project readme to point to the right line in the b2b sample app.
> Add missing redirect types to the ui readmes and update B2B UI sample app.

- Sources/StytchCore/Networking/NetworkingRouter.swift
- Sources/StytchCore/SharedModels/Errors/StytchAPIError.swift
Linear Ticket: [LINEAR_NUMBER](https://linear.app/stytch/issue/YOUR_TICKET)
1. This PR is not mission critical, it just makes some things around error checking in `NetworkingRouter` slightly more readable.
2. It also creates a convenience initializer for `StytchAPIError` to create a `unknownErrorWithStatusCode` and `debugInfo`. Logic that was previously in the `NetworkingRouter`.
> Make error handling code in NetworkingRouter more readable.

- Sources/StytchCore/SharedModels/Errors/StytchSDKError.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Stytch/DemoApps/StytchBiometrics/ViewController.swift
1. Found a bug in `registrationAvailable` where we were referring to the wrong keychain value, we should have been using `privateKeyRegistration` which is the value needed for authentication and not the `biometricKeyRegistration` which is simply the biometric registration id.
2. Expose the `biometricRegistrationId` from `StytchClient.Biometrics`.
3. Added some additional comments to the biometrics client.
4. Added some additional logging to the sample app for `registrationAvailable`.
> Modify logic for biometrics registrationAvailable

- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Common.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/BaseViewController/BaseViewController+Discovery.swift
- Sources/StytchUI/StytchB2BUIClient/StytchB2BUIClient/StytchB2BUIClient+Configuration.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/Discovery/CreateOrganizationsViewController/CreateOrganizationsViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/Discovery/DiscoveredOrganizations/DiscoveredOrganizationsViewController.swift
- Stytch/DemoApps/StytchB2BUIDemo/ContentView.swift
[directOrgCreationOnZeroMemberships in iOS SDK UI](https://linear.app/stytch/issue/SDK-2381/directorgcreationonzeromemberships-in-ios-sdk-ui)
1. Add `directCreateOrganizationForNoMembership` to the B2B UI configuration object.
2. Consolidate create organization logic which was duplicated across 3 places.
3. Add some comments to the `computedAuthFlowType`.
> directCreateOrganizationForNoMembership for B2BUI

- .github/actions/bootstrap/action.yml
Just bumping it to the latest version
> [INFRA-2462] ci: bump actions/cache to v4

- Sources/StytchCore/SharedModels/Configuration.swift
- Sources/StytchCore/StytchClientType.swift
- Tests/StytchCoreTests/KeychainClientTestCase.swift
[[iOS] Add checking/early return for multiple configure calls being made](https://linear.app/stytch/issue/SDK-2391/[ios]-add-checkingearly-return-for-multiple-configure-calls-being-made)
1. Add `Equatable` conformance to the `Configuration` object.
2. In `StytchClientType` change logic to create a new configuration from the passed in values for `mutating func configure(publicToken: String, hostUrl: URL?, dfppaDomain: String?)` and only assign a new configuration and proceed with set up steps if the configuration is different.
3. Add a unit test in `KeychainClientTestCase` to make sure the keychain client values don't reset when the same public token is used to call configure multiple times.
> Block multiple calls to configure

- Sources/StytchCore/SharedModels/Errors/StytchAPIErrorType.swift
Linear Ticket: [SDK-2417](https://linear.app/stytch/issue/SDK-2417)
1. Ran the autogen script from https://github.com/stytchauth/api/pull/6797 to show what the output of that script is gonna be.
> SDK-2417 Add first round of autogenerated API error types to repo

- Sources/StytchCore/StartupClient.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Sources/StytchCore/StytchClientType.swift
- Stytch/DemoApps/StytchDemo/ContentView.swift
[[iOS] Don't override valid bootstrap data if coming to the foreground with no network connection](https://linear.app/stytch/issue/SDK-2434/[ios]-dont-override-valid-bootstrap-data-if-coming-to-the-foreground)
1. Modify logic in the bootstrap response where as before it was always overriding the bootstrap data stored locally if a call failed. Now it will only assign the default data if there is none saved.
2. Consolidate duplicate codes based on client type across `StytchB2BClient` and `StytchClient` into a single `start` function.
3. Check to make sure the captcha siteKey is not only not nil but also not an empty string.
> Refactor some bootstrap funk, consolidate code

- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+ThirdParty+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+ThirdParty.swift
- Sources/StytchCore/StytchClient/OAuth/OAuth+ThirdParty.swift
- Tests/StytchCoreTests/BaseTestCase.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
[iOS: OAuth provider params don't work](https://linear.app/stytch/issue/SDK-2435/ios-oauth-provider-params-dont-work)
1. We had the provider params being added a value with a key "provider_params" which was wrong, they should be just added to the dictionary of queryParameters that gets built.
> Fix OAuth provider params

- Sources/StytchCore/Extensions/Dictionary+Stytch.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+ThirdParty+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth+ThirdParty.swift
- Sources/StytchCore/StytchClient/OAuth/OAuth+ThirdParty.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
[iOS: OAuth provider params don't work](https://linear.app/stytch/issue/SDK-2435/ios-oauth-provider-params-dont-work)
1. I had misunderstood how the provider params need to be formatted in a previous pr, so we are fixing them in this one.
> Fix Oauth provider params (take 2)

- Sources/StytchUI/Extensions/Array+StytchUI.swift
- Sources/StytchUI/StytchB2BUIClient/StytchB2BUIClient/StytchB2BUIClient+ProductOrdering.swift
- Sources/StytchUI/StytchUIClient/StytchUIClient+Configuration.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/AuthHomeViewController/AuthHomeViewController.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/AuthHomeViewController/AuthHomeViewModel.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/AuthInputViewController/AuthInputViewController.swift
- Stytch/DemoApps/StytchUIDemo/ContentView.swift
[[iOS] Follow order of products in prebuilt UI components](https://linear.app/stytch/issue/SDK-2446/[ios]-follow-order-of-products-in-prebuilt-ui-components)
1. Bring component ordering to the B2C UI, including the ordering of the tab bar components.
2. In the tab bar OTP options go first and then if email was not an OTP option but EML was enabled it will be added last.
> Respect the order of products for the b2c ui

- Sources/StytchCore/StytchB2BClient/Models/OrganizationType.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SearchManager.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/StateManagement/OrganizationManager.swift
- Sources/StytchUI/StytchB2BUIClient/StytchB2BUIClient/StytchB2BUIClient+Configuration.swift
- Tests/StytchCoreTests/B2BSearchManagerTestCase.swift
[[iOS] Update org search by slug response to include slug in response object.](https://linear.app/stytch/issue/SDK-2464/[ios]-update-org-search-by-slug-response-to-include-slug-in-response)
1. Mirrors changes made in: https://github.com/stytchauth/api/pull/6888.
2. This allows me to unify logic between the full org object and the org object returned by the search by slug endpoint.
> Add org slug to generic OrganizationType

- Sources/StytchCore/SharedModels/Errors/StytchSDKError.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Tests/StytchCoreTests/BiometricsTestCase.swift
[[iOS] Biometrics - don't allow register to be called if local registration exists.](https://linear.app/stytch/issue/SDK-2369/[ios]-biometrics-dont-allow-register-to-be-called-if-local)
> Prevent biometric registration if the user is already enrolled.

- Sources/StytchUI/StytchB2BUIClient/ViewControllers/EmailOTPEntryViewController/EmailOTPEntryViewController.swift
[iOS: Countdown for B2B Email OTP code expiry should be 10 minutes, not 2](https://linear.app/stytch/issue/SDK-2472/ios-countdown-for-b2b-email-otp-code-expiry-should-be-10-minutes-not-2)
> Change timeout of email otp to 10 minutes

- Sources/StytchCore/SessionManager.swift
- Sources/StytchCore/SharedModels/SessionToken.swift
- Sources/StytchCore/StytchClientType.swift
[[iOS SDK] request is from SDK and contains malformed credential errors during OTPsSMSLoginOrCreate requests](https://linear.app/stytch/issue/SDK-2488/[ios-sdk]-request-is-from-sdk-and-contains-malformed-credential-errors)
> Safeguards on caching and reading empty tokens

- .github/actions/bootstrap/action.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Makefile
- Package.swift
- Sources/StytchCore/DFPClient/CAPTCHA.swift
- Stytch/Stytch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
[[iOS] Bump recaptcha-enterprise to 18.7](https://linear.app/stytch/issue/SDK-2493/[ios]-bump-recaptcha-enterprise-to-187)
This resolves issue: https://github.com/stytchauth/stytch-ios/issues/412
1. Bumping the `recaptcha-enterprise-mobile-sdk` was simple and the one line change that went with it.
2. But the changes needed in the GitHub infra took a while to resolve.
3. Now we are on the most recent version of Xcode, 16.2, which matches the local dev environment.
> Bump recaptcha-enterprise to 18.7 - Bump Github Xcode version to 16.2

- Sources/StytchCore/SessionManager.swift
- Sources/StytchCore/StartupClient.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP/StytchB2BClient+OTP+SMS.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Passwords/StytchB2BClient+Passwords+Discovery.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Passwords/StytchB2BClient+Passwords.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SSO/StytchB2BClient+SSO.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Sources/StytchCore/StytchClient/CryptoWallets/StytchClient+CryptoWallets.swift
- Sources/StytchCore/StytchClient/MagicLinks/StytchClient.MagicLinks+Email.swift
- Sources/StytchCore/StytchClient/OTP/SytchClient+OTP.swift
- Sources/StytchCore/StytchClient/Passkeys/StytchClient+Passkeys.swift
- Sources/StytchUI/StytchB2BUIClient/StytchB2BUIClient/StytchB2BUIClient+Configuration.swift
- Sources/StytchUI/StytchUIClient/StytchUIClient+Configuration.swift
- Tests/StytchCoreTests/B2BDiscoveryTestCase.swift
- Tests/StytchCoreTests/CryptoWalletsTestCase.swift
- Tests/StytchCoreTests/MagicLinksTestCase.swift
- Tests/StytchCoreTests/OTPTestCase.swift
[[iOS] Refactor Session Manager](https://linear.app/stytch/issue/SDK-2491/[ios]-refactor-session-manager)
This refactor was brought on by investigating: [[iOS] Intermediate Session Token Error (Prebuilt B2B UI Components)](https://linear.app/stytch/issue/SDK-2370/[ios]-intermediate-session-token-error-prebuilt-b2b-ui-components) I think that issue still exists but this will make it easier to find and fix.
1. Refactor and restructure the `SessionManager` class that is the internal interface for both verticals and their logic around session objects and session tokens. The actual persistence happens in the `KeychainClient` which I want to refactor also but in a subsequent PR.
2. The values that the `SessionManager` exposes internally from the keychain are: `sessionToken`, `sessionJwt`, …
> Session Manager Refactor

- Package.swift
- README.md
[[iOS] Bump minimum supported os versions - iOS 15.0](https://linear.app/stytch/issue/SDK-2496/[ios]-bump-minimum-supported-os-versions-ios-150)
1. Bump the minimum supported versions in the `Package.swift` most importantly we bumped iOS to 15.
> Bump minimum supported os versions - iOS 15.0

- Sources/StytchUI/Shared/BaseViewController.swift
- Sources/StytchUI/StytchB2BUIClient/StytchB2BUIClient/StytchB2BUIClient+Configuration.swift
- Sources/StytchUI/StytchB2BUIClient/StytchB2BUIClient/StytchB2BUIClient.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BAuthHomeViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthRootViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/ErrorViewController/ErrorViewController.swift
- Sources/StytchUI/StytchUIClient/StytchUIClient+Configuration.swift
- Sources/StytchUI/StytchUIClient/StytchUIClient.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/AuthHomeViewController/AuthHomeViewController.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/AuthRootViewController.swift
- Stytch/DemoApps/B2BWorkbench/ViewControllers/AuthMethodControllers/B2BUIViewController.swift
- Stytch/DemoApps/StytchB2BUIDemo/ContentView.swift
- Stytch/DemoApps/StytchUIDemo/ContentView.swift
[[iOS] Prebuilt UI can be manually dismissed on both SwiftUI and UIKit.](https://linear.app/stytch/issue/SDK-2303/[ios]-prebuilt-ui-can-be-manually-dismissed-on-both-swiftui-and-uikit)
This is a good start but there is some follow up work needed here: [[iOS] Consider ways to surface authentication events better from the pre built ui](https://linear.app/stytch/issue/SDK-2498/[ios]-consider-ways-to-surface-authentication-events-better-from-the). Right now we don't have a good way of surfacing events to the calling developer where they may choose to log errors or dismiss the UI manually and we should add that next.
1. Each of the UI clients `StytchUIClient` and `StytchB2BUIClient` have methods for showing the prebuilt UI from SwiftUI and UIKit.
2. For SwiftUI I added …
> Fix issues with prebuilt UI being manually dismissed

- Sources/StytchCore/KeychainClient/KeychainClient+Item.swift
- Sources/StytchCore/KeychainClient/KeychainClient+Live.swift
- Sources/StytchCore/KeychainClient/KeychainClient+Types.swift
- Sources/StytchCore/KeychainClient/KeychainClient.swift
- Sources/StytchCore/KeychainClient/KeychainMigrations/KeychainMigration.swift
- Sources/StytchCore/KeychainClient/KeychainMigrations/KeychainMigration1.swift
- Sources/StytchCore/KeychainClient/KeychainMigrations/KeychainMigration2.swift
- Sources/StytchCore/KeychainClient/KeychainMigrations/KeychainMigration3.swift
- Sources/StytchCore/ObjectStorage.swift
- Sources/StytchCore/PKCE/PKCEPairManager.swift
- Sources/StytchCore/SessionManager.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Tests/StytchCoreTests/B2BMagicLinksTestCase.swift
- Tests/StytchCoreTests/BiometricsTestCase.swift
- Tests/StytchCoreTests/CryptoWalletsTestCase.swift
- Tests/StytchCoreTests/DeeplinkHandlerTestCase.swift
- Tests/StytchCoreTests/KeychainClient+Mock.swift
- Tests/StytchCoreTests/KeychainClientTestCase.swift
- Tests/StytchCoreTests/MagicLinksTestCase.swift
- Tests/StytchCoreTests/OTPTestCase.swift
[[iOS] Refactor Keychain Client](https://linear.app/stytch/issue/SDK-2492/[ios]-refactor-keychain-client) **1/2**
There are no functional changes in this PR.
1. In this first pr refactoring elements of the `KeychainClient` I focused on mostly renaming some things and moving code around for the second round of refactoring and readability.
2. In the `KeychainClient` there were many overlapping definitions of things like `get` and `set` which made confusing in the code which one was getting called when so I split them into more explicit naming:
3. `get` -> `getQueryResults`
4. `get` -> `getStringValue`
5. `set` -> `setStringValue`
6. `set` -> `setPrivateKeyRegistration`
7. `getQueryResult` -> `getFirstQueryResult`
8. In `KeychainClient+Live.swift` I changed some things from completion blocks …
> Improve KeychainClient names and structure

- Sources/StytchCore/DFPClient/DFPClient.swift
1. There was a warning in the DFP client after making the minimum target for the sdk iOS 15 that I fixed here, tested and it works.
> Update dfp client for iOS 15

- Sources/StytchCore/SessionManager.swift
- Sources/StytchCore/SharedModels/SessionToken.swift
[[iOS] updateSession - jwt_token should be optional](https://linear.app/stytch/issue/SDK-2507/[ios]-updatesession-jwt-token-should-be-optional)
the JWT is somewhat of a superfluous part of the iOS SDK. It is returned from authentication responses and we cache and expose it via the SDK but it is never used internally. This PR makes some changes around the `SessionTokens` object  that holds both tokens and the object that is used to "update" as session. Which is when you may have received tokens from outside the SDK for some reason and want to inject them into the SDK.
1. In the `SessionTokens` object make the `jwt` optional.
> Make jwt optional in SessionTokens

- Sources/StytchCore/Networking/NetworkingRouter.swift
- Sources/StytchCore/SessionManager.swift
- Sources/StytchCore/SharedModels/Errors/StytchAPIError.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Sessions.swift
- Sources/StytchCore/StytchClient/StytchClient+Sessions.swift
- Tests/StytchCoreTests/SessionManagerTestCase.swift
[[iOS][Android] Investigate which network failures should clear session](https://linear.app/stytch/issue/SDK-2368/[ios][android]-investigate-which-network-failures-should-clear-session)
This behavior moves from clearing the session on all 401s from any endpoint, regardless of error type,
to only clearing the session if we get a 401 with an unrecoverable error type, and only during session authenticate or session revoke calls.
Additionally, for revoke, we don't always clear the session on failure. We only clear it if:
- The error is unrecoverable, or
- The developer passes a forceClear flag to explicitly clear the session even if revoke fails.
This gives developers control over how strictly they want to enforce backend revocation.
> Only clear session for unrecoverable error types

- Sources/StytchCore/SessionManager.swift
This is a small but important PR where we now assign the tokens before we publish the session objects. We were assigning them after we published and the tokens were nil if you logged them in the publisher from the sample app.
> Assign the tokens before we fire the session event

- Sources/StytchUI/Inputs/EmailInput.swift
- Sources/StytchUI/Inputs/PhoneNumberInput.swift
- Sources/StytchUI/Inputs/SecureTextInput.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/B2BPasswordsViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/EmailConfirmationViewController/EmailConfirmationViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordForgotViewController/PasswordForgotViewModel.swift
- Stytch/DemoApps/StytchB2BUIDemo/ContentView.swift
- Stytch/DemoApps/StytchB2BUIDemo/Info.plist
[[iOS] Fix erroneous JIT provisioning error in B2B UI SDK](https://linear.app/stytch/issue/SDK-2589/[ios]-fix-erroneous-jit-provisioning-error-in-b2b-ui-sdk)
1. Modify logic to no longer check for memberPasswordId if the search member call returns a member. The existence of a member is enough to attempt password authenticate or send a password reset email.
2. Also found some UI operations in the text fields that we not happening on the main thread.
> Remove checks for memberPasswordId

- Sources/StytchCore/StartupClient.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
[[iOS] Look into performance improvements for configure call](https://linear.app/stytch/issue/SDK-2603/[ios]-look-into-performance-improvements-for-configure-call)
[[iOS] Add details to the documentation for "isInitialized"](https://linear.app/stytch/issue/SDK-2600/[ios]-add-details-to-the-documentation-for-isinitialized)
1. The `sessions.authenticate` call and the `bootstrap` call do not need to happen in sequence as they were happening now.
2. `sessions.authenticate` does not require dfppa or captcha so we can safely kick off `sessions.authenticate` in parallel. 
3. This bring down the time for the `isInitializedPublisher` by about 150ms.
> Run bootstrap and sessions.authenticate in parallel on start

- Sources/StytchCore/Networking/NetworkingClient+Live.swift
- Tests/StytchCoreTests/NetworkingClient+LiveTestCase.swift
1. Modify the logic the in `NetworkingClient+Live` to only configure an endpoint for DFPPA disabled if the endpoint uses DFPPA but its disabled from the bootstrap call.
> Fix NetworkingClient logic for dfppa

- Sources/StytchCore/Networking/NetworkRequestHandler.swift
- Sources/StytchCore/Networking/NetworkingClient+Live.swift
- Tests/StytchCoreTests/NetworkRequestHandlerTestCase.swift
- Tests/StytchCoreTests/NetworkingClient+LiveTestCase.swift
[[iOS] Refactor NetworkingClient](https://linear.app/stytch/issue/SDK-2500/[ios]-refactor-networkingclient)
Part of incremental progress in refactoring networking.
1. Consolidate request handling into `NetworkRequestHandler` including the `defaultRequestHandler`.
2. Move properties into protocol definition so that we are not passing everything into each function call.
3. Use the `NetworkRequestHandler` extension as the default / live implementation.
> Refactor NetworkRequestHandler

- Resources/Sourcery/Templates/AsyncVariants.stencil
- Sources/StytchCore/Environment.swift
- Sources/StytchCore/Generated/StytchClient.Biometrics.authenticate+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.Biometrics.register+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.Biometrics.removeRegistration+AsyncVariants.generated.swift
- Sources/StytchCore/SharedModels/Errors/StytchSDKError.swift
- Sources/StytchCore/StytchClient/Biometrics/LAContextEvaluating.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Stytch/DemoApps/StytchUIDemo/ContentView.swift
- Tests/StytchCoreTests/BaseTestCase.swift
[[iOS] Biometrics - Show biometrics prompt on register.](https://linear.app/stytch/issue/SDK-2679/ios-biometrics-show-biometrics-prompt-on-register)
1. When the developer calls register we should show the biometrics prompt.
2. Added a protocol for testing called `LAContextEvaluating` that `LAContext` can conform to by default. Which made it possible to mock the methods within `LAContext`.
3. Added an instance of `LAContextEvaluating` to the `Environment` called `localAuthenticationContext` which in live is just an instance of `LAContext`.
4. Modified the Sorcery template to include an option to add a compiler directive to exclude bot `watchOS` and `tvOS`, before you could only exclude `watchOS`.
5. Remove redundant `AccessPolicy` from the `StytchClient.Biometrics.RegisterParameters` and …
> Show faceid prompt on register

- Sources/StytchCore/StytchClient/Biometrics/LAContextEvaluating.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Sources/StytchUI/Components/ImageAsset.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthRootViewController.swift
- Sources/StytchUI/StytchUIClient/StytchUIClient+Configuration.swift
- Sources/StytchUI/StytchUIClient/StytchUIClient.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/AuthHomeViewController/AuthHomeViewController.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/AuthHomeViewController/AuthHomeViewModel.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/AuthInputViewController/AuthInputViewController.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/AuthRootViewController.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/BiometricsRegistrationViewController/BiometricsRegistrationViewController.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/BiometricsRegistrationViewController/BiometricsRegistrationViewModel.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/OAuthViewController/OAuthViewController.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/OAuthViewController/OAuthViewModel.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/OTPCodeViewController/OTPCodeViewController.swift
- Stytch/DemoApps/StytchUIDemo/ContentView.swift
- Stytch/DemoApps/StytchUIDemo/Info.plist
- Tests/StytchCoreTests/BaseTestCase.swift
[SDK-2680: \[iOS\] Productionize hackweek project for biometrics in the consumer prebuilt UI.](https://linear.app/stytch/issue/SDK-2680/ios-productionize-hackweek-project-for-biometrics-in-the-consumer)
1. Add support to the consumer prebuilt UI for biometrics registration and authentication.
2. You can configure the it so that you do or do not register after authentication via the `BiometricsOptions`.
3. If you choose not to register via the prebuilt UI you will have to call register from elsewhere.
4. In either case if the user is somehow registered and you include in the product config `.biometrics` then a button will be added to the home screen to authenticate with biometrics.
> Add Biometrics To The Consumer Prebuilt UI

- Sources/StytchCore/LocalStorage.swift
- Sources/StytchCore/SharedModels/StytchClientConfiguration.swift
Linear Ticket: [SDK-2689](https://linear.app/stytch/issue/SDK-2689)
1. Adds support for custom domains
> SDK-2689 Enable custom domains as endpoint options for API

- Sources/StytchCore/CaptchaClient.swift
- Sources/StytchCore/DFPClient.swift
- Sources/StytchCore/Environment.swift
- Sources/StytchCore/Networking/NetworkRequestHandler.swift
- Sources/StytchCore/Networking/NetworkingClient.swift
- Sources/StytchCore/PasskeysClient/PasskeysClient+Live.swift
- Sources/StytchCore/StartupClient.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+DFP.swift
- Sources/StytchCore/StytchClient/DFP/StytchClient+DFP.swift
- Sources/StytchCore/StytchClientType.swift
- Stytch/Stytch.xcodeproj/project.pbxproj
Linear Ticket: [SDK-2744](https://linear.app/stytch/issue/SDK-2744)
When building macCatalyst apps, the os is still considered iOS, but the binary framework is not available for macOS, so it fails to link correctly.
1.  Instead of relying on `os()` macros, use explicit checks for being able to import the desired modules
2. Fixes an additional issue with the passkeys implementation on macCatalyst, where `performAutoFillAssistedRequests` is explicitly disallowed for that platform
> SDK-2744 Add explicit canImport checks around DFP

- .github/workflows/cut_version.yml
Linear Ticket: [INFRA-2910](https://linear.app/stytch/issue/INFRA-2910)
1. I've added access to the org's `PERSONAL_ACCESS_TOKEN` secret to this repo
2. I've updated the workflow that uses the CI token to use this org-wide secret instead for the ci-stytch user
> [INFRA-2910] update CI token to org Github token

- Sources/StytchCore/EncryptedUserDefaultsClient/EncryptedUserDefaultsClientImplementation.swift
- Sources/StytchCore/Environment.swift
- Sources/StytchCore/KeychainClient/KeychainClient.swift
- Sources/StytchCore/KeychainClient/KeychainClientImplementation.swift
- Sources/StytchCore/StytchClientType.swift
- Tests/StytchCoreTests/KeychainClient+Mock.swift
Linear Ticket: [SDK-2792](https://linear.app/stytch/issue/SDK-2792)
1. Add a DispatchQueue to EncryptedUserDefaults the same way we did to the KeychainClient
2. Don't trigger the startup flow (or attempt to retrieve the encryption key) until we are sure that protectedData is available
> SDK-2792 UserDefaults guardrails and waiting for protected data

- .github/CODEOWNERS
- Sources/StytchCore/EncryptedUserDefaultsClient/EncryptedUserDefaultsClient.swift
- Sources/StytchCore/EncryptedUserDefaultsClient/EncryptedUserDefaultsClientImplementation.swift
- Sources/StytchCore/EncryptedUserDefaultsClient/EncryptedUserDefaultsItem.swift
- Sources/StytchCore/Networking/NetworkingRouter.swift
- Sources/StytchCore/ObjectStorage.swift
- Sources/StytchCore/SessionManager.swift
Linear Ticket: No ticket
1. Adopt the session storm protection from JS SDK
2. Bubble up exact causes for info being unavailable, and attempt to determine if it's expected or not
> Guard against session storms and expose reasons for unavailable cases

- .github/workflows/test.yml
- Mintfile
- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
- Sources/StytchCore/Environment.swift
- Sources/StytchCore/PollingClient/PollingClient.swift
- Tests/StytchCoreTests/B2BDiscoveryTestCase.swift
- Tests/StytchCoreTests/B2BMagicLinksTestCase.swift
- Tests/StytchCoreTests/B2BOAuthTestCase.swift
- Tests/StytchCoreTests/B2BOTPTestCase.swift
- Tests/StytchCoreTests/B2BPasswordsTestCase.swift
- Tests/StytchCoreTests/B2BRecoveryCodesTestCase.swift
- Tests/StytchCoreTests/B2BSSOTestCase.swift
- Tests/StytchCoreTests/B2BSessionsTestCase.swift
- Tests/StytchCoreTests/B2BTOTPTestCase.swift
- Tests/StytchCoreTests/BaseTestCase.swift
- Tests/StytchCoreTests/BiometricsTestCase.swift
- Tests/StytchCoreTests/CryptoWalletsTestCase.swift
- Tests/StytchCoreTests/DeeplinkHandlerTestCase.swift
- Tests/StytchCoreTests/MagicLinksTestCase.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
- Tests/StytchCoreTests/OTPTestCase.swift
- Tests/StytchCoreTests/PasskeysTestCase.swift
- Tests/StytchCoreTests/PasswordsTestCase.swift
- Tests/StytchCoreTests/PollingClientTestCase.swift
- Tests/StytchCoreTests/SessionManagerTestCase.swift
- Tests/StytchCoreTests/TOTPTestCase.swift
- Tests/StytchCoreTests/XCTestHelpers.swift
Linear Ticket: [SDK-2809](https://linear.app/stytch/issue/SDK-2809)
1. PollingClients theoretically specified a custom serial queue to use, but weren't actually using them. `start()` just ran on whatever queue was currently active, `stop()` ran on main explicitly. The first change was to ensure all methods use the same queue.
2. Even though they're running in the same queue, there's no guarantee they'd run on the same thread, so NSTimer might still have issues. So, swap it for a DispatchSourceTimer which is tied to a dispatch queue instead of a thread. Because of the change above, we should now be confident that timers will be started and canceled correctly.
- This is a hotfix for a customer on 0.70.0 to prevent them having to upgrade to latest and incur any potential breaking changes. …
> Attempt to fix timer invalidation crash

- Sources/StytchCore/EncryptedUserDefaultsClient/EncryptedUserDefaultsClient.swift
- Sources/StytchCore/Networking/NetworkingRouter.swift
- Sources/StytchCore/SharedModels/DeviceHistory.swift
- Sources/StytchCore/SharedModels/Response.swift
- Sources/StytchCore/StytchB2BClient/Models/B2BAuthenticateResponse.swift
- Sources/StytchCore/StytchB2BClient/Models/B2BMFAAuthenticateResponse.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP/StytchB2BClient+OTP+Email.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+RecoveryCodes.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Sources/StytchCore/StytchClient/Models/AuthenticateResponse.swift
- Sources/StytchCore/StytchClient/OAuth/OAuth+Apple.swift
- Sources/StytchCore/StytchClient/OAuth/StytchClient+OAuth.swift
- Sources/StytchCore/StytchClient/Passwords/StytchClient+Passwords.swift
- Sources/StytchCore/StytchClient/TOTP/StytchClient+TOTP.swift
- Tests/StytchCoreTests/B2BMagicLinksTestCase.swift
- Tests/StytchCoreTests/B2BOAuthTestCase.swift
- Tests/StytchCoreTests/B2BOTPTestCase.swift
- Tests/StytchCoreTests/B2BRecoveryCodesTestCase.swift
- Tests/StytchCoreTests/BaseTestCase.swift
- Tests/StytchCoreTests/BiometricsTestCase.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
- Tests/StytchCoreTests/PasswordsTestCase.swift
- Tests/StytchCoreTests/TOTPTestCase.swift
- Tests/StytchUIUnitTests/StytchUIClientTests/BaseTestCase.swift
[User Device History changes for iOS](https://linear.app/stytch/issue/SDK-2823/user-device-history-changes-for-ios)
Android PR: https://github.com/stytchauth/stytch-android/pull/363
1. Create `DeviceHistory` and `DeviceAttributeDetails` objects.
2. Add `DeviceHistory` to the B2C `AuthenticateResponseDataType` as `userDevice`
3. Add `DeviceHistory` to the B2B `B2BAuthenticateResponseDataType` and `B2BMFAAuthenticateResponseDataType` as `memberDevice`
I decided to go with the approach of adding these as optionals to the generic response types rather than bifurcating all response types to accommodate the reality that only certain response types have `DeviceHistory` in their response type. I decided to do this to avoid unnecessary complexity in the code for a feature that mobile users are …
> User-Member Device History

- Sources/StytchCore/KeychainClient/KeychainClient.swift
- Sources/StytchCore/KeychainClient/KeychainClientImplementation.swift
- Sources/StytchCore/KeychainClient/KeychainItem.swift
- Sources/StytchCore/StytchClientType.swift
- Stytch/DemoApps/StytchBiometrics/ViewController.swift
- Stytch/DemoApps/StytchUIDemo/ContentView.swift
- Tests/StytchCoreTests/KeychainClient+Mock.swift
- Tests/StytchCoreTests/KeychainClientTestCase.swift
[[iOS] Keychain migration 4 is failing with empty encryption key](https://linear.app/stytch/issue/SDK-2849/ios-keychain-migration-4-is-failing-with-empty-encryption-key)
[[iOS] Session token failing to write to the encrypted user defaults](https://linear.app/stytch/issue/SDK-2850/ios-session-token-failing-to-write-to-the-encrypted-user-defaults)
1. We are removing the UIApplication.shared.isProtectedDataAvailable check because it is not needed for the encryption key.
2. The encryption key uses AfterFirstUnlock accessibility, so it becomes available once the device is unlocked after reboot and remains accessible even if the device is later locked.
3. No user presence access control (biometric or passcode) is applied, which ensures the key can always be read silently.
4. Reads are …
> Remove logic around isProtectedDataAvailable

- Sources/StytchCore/Environment.swift
- Sources/StytchCore/KeychainClient/KeychainClientImplementation.swift
- Sources/StytchCore/StytchClient/Biometrics/LAContextEvaluating.swift
- Sources/StytchCore/StytchClient/Biometrics/LocalAuthenticationContextManager.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Tests/StytchCoreTests/BaseTestCase.swift
- Tests/StytchCoreTests/BiometricsTestCase.swift
[[iOS] Make biometric prompts customizable.](https://linear.app/stytch/issue/SDK-2904/ios-make-biometric-prompts-customizable)
1. Moved the management of the shared  `LAContext` to the `LocalAuthenticationContextManager`.
2. Create `LAContextPromptStrings` so that the calling developer can configure the strings for an `LAContext`.
> Make biometrics prompt strings more customizable

- Sources/StytchCore/PollingClient/PollingClient+Live.swift
- Sources/StytchCore/SharedModels/StytchClientConfiguration.swift
[[iOS] Optionally extend the session with the heartbeat via the client config](https://linear.app/stytch/issue/SDK-2909/ios-optionally-extend-the-session-with-the-heartbeat-via-the-client)
1. Now the developer can configure if they want the heartbeat to extend the session and by how much rather than just validating the session.
> Configureable session extension
