stytchauth/stytch-ios

- Stytch/Source/Strings/en.strings
Linear Ticket: [MOB-22](https://linear.app/stytch/issue/MOB-22)
> Update Stytch Button text to 'Continue with email'

- .github/workflows/docs.yml
- .github/workflows/release.yml
- Makefile
- README.md
- Stytch.podspec
> [fix] Fix docs release upload & pod docs url

- .spi.yml
- Package.swift
> [build] Add Swift Package Index manifest

- README.md
- Sources/StytchCore/Documentation.docc/StytchCore.md
> [docs] Fix broken links

- README.md
> [docs] Add passwords to README supported products

- Sources/StytchCore/Documentation.docc/StytchCore.md
- Sources/StytchCore/Generated/StytchClient.handle+AsyncVariants.generated.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
> [docs] Fix documentation links

- Sources/StytchCore/KeychainClient/KeychainClient+Live.swift
> Fix keychain compilation on watchOS and tvOS

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Bump minor version

- .github/release.yml
- .github/workflows/cut_version.yml
- .github/workflows/release.yml
- Brewfile
> [platform] Add further release automation fixes

- .github/workflows/publish.yml
- Gemfile
- Gemfile.lock
- Scripts/publish-to-carthage
Build out support using the s3 ruby sdk and fixup the publish workflow
> [platform] Enable auto publish to carthage

- .github/workflows/cut_version.yml
- Sources/StytchCore/User.swift
- Tests/StytchCoreTests/BaseTestCase.swift
- Tweaks cut-version workflow
- Adds password to user type
> Fix cut version

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.6.0

- StytchDemo/Client/Shared/OAuthAuthenticationView.swift
- Add new OAuth providers to demo app (#88)
- Move to confirmation dialog for Third Party providers
> Add new OAuth providers to demo app

- .github/workflows/docs.yml
- .github/workflows/test.yml
> [platform] Fix ci on main

- .github/workflows/docs.yml
- .github/workflows/test.yml
> [platform] Try to fix CI

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.7.0

- .github/actions/bootstrap/action.yml
Cache brew Cellar dirs for items in Brewfile for modest gains in speed vs downloading/installing each time.
Briefly attempted to run brew link or brew install directly vs using brew bundle. I don't think this is necessarily the most maintainable and the gains were minimal, so likely not worth it long term.
> [platform] Cache brew install

- .github/workflows/publish.yml
- .github/workflows/release.yml
- Sources/StytchCore/AuthenticationFactor.swift
- Sources/StytchCore/Documentation.docc/StytchCore.md
- Sources/StytchCore/JSON.swift
- Sources/StytchCore/Session.swift
- Sources/StytchCore/StytchClient/MagicLinks/Email/Email.swift
- Sources/StytchCore/User.swift
This first and foremost fixes release mode compilation caused by some `#if DEBUG` statements and includes some other cleanup/fixes.
- Make more types Codable always
- Fix documentation links
- Rename workflows for clarity
> [fix] Fix release compilation

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.8.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.9.0

- .github/workflows/docs.yml
Crossing my fingers this works. Was running locally using [act](https://github.com/nektos/act), and had to add in some additional work to make this function, but I believe this should work as is in a normal GH actions environment.
> fix: Fix docs workflow by fetching tags explicitly

- .github/workflows/docs.yml
> fix: Fix docs workflow by using correct path

- .github/workflows/docs.yml
> fix: Fix docs workflow by zipping up artifact before uploading

- .github/workflows/docs.yml
> fix: Fix docs workflow by using underscore in ref_label to appease jq

- .github/workflows/docs.yml
> fix: Add git config user name and email

- README.md
- Sources/StytchCore/DeeplinkHandledStatus.swift
- Sources/StytchCore/Documentation.docc/StytchCore.md
- Sources/StytchCore/Identifier.swift
- Sources/StytchCore/JSON.swift
- Sources/StytchCore/StytchB2BClient/Models/B2BAuthenticateResponse.swift
- Sources/StytchCore/StytchB2BClient/Models/Member.swift
- Sources/StytchCore/StytchB2BClient/Models/MemberSession.swift
- Sources/StytchCore/StytchB2BClient/Models/Organization.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+MagicLinks.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Members.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Organizations.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Sources/StytchCore/StytchClient/Models/AuthenticateResponse.swift
- Sources/StytchCore/StytchClient/Models/User.swift
- Sources/StytchCore/StytchClient/Passkeys/StytchClient+Passkeys.swift
- Sources/StytchCore/StytchClientCommon/Models/Response.swift
- Sources/StytchCore/StytchClientCommon/Models/SessionToken.swift
- Sources/StytchCore/Union.swift
As titled
Completes: SDK-855, SDK-856
> [docs] Update docs and include B2B

- .swiftformat
- .swiftlint.yml
- Sources/StytchCore/Documentation.docc/Tutorials/stytch/advanced/manage-sessions-manually.tutorial
- Sources/StytchCore/Documentation.docc/Tutorials/stytch/basics/adding-more-methods/add-biometrics.tutorial
- Sources/StytchCore/Documentation.docc/Tutorials/stytch/basics/getting-started/initial-setup.tutorial
- Sources/StytchCore/Documentation.docc/Tutorials/stytch/intermediate/manage-the-current-user.tutorial
- Sources/StytchCore/Documentation.docc/Tutorials/stytch/intermediate/step-up-auth-mfa.tutorial
> Fix lint for tutorials

- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Sources/StytchCore/StytchClientCommon/StytchClientType.swift
Adds helper that more easily indicates if a given deeplink url is intended for Stytch
> [feat] Add canHandle(url:) helper function

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.10.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.11.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.12.0

- Makefile
- README.md
- Scripts/publish-to-carthage
- Sources/StytchCore/ClientInfo/ClientInfo+SDK.swift
- Sources/StytchCore/Documentation.docc/StytchCore.md
- Sources/StytchCore/Documentation.docc/Tutorials/stytch/basics/getting-started/add-eml.tutorial
- Sources/StytchCore/Documentation.docc/Tutorials/stytch/basics/getting-started/initial-setup.tutorial
- Sources/StytchCore/StytchClientCommon/Models/StytchError.swift
- Stytch.podspec
Updates all references of stytch-swift to stytch-ios, now that the repo name has changed.
> Update stytch-swift to stytch-ios

- README.md
- Sources/StytchCore/Documentation.docc/StytchCore.md
> Missed some swift/iOS references

- Brewfile.lock.json
- Sources/StytchCore/Generated/StytchClient.UserManagement.update+AsyncVariants.generated.swift
- Sources/StytchCore/JSON.swift
- Sources/StytchCore/StytchClient/Models/User.swift
- Sources/StytchCore/StytchClient/User/StytchClient+User.swift
- Tests/StytchCoreTests/BaseTestCase.swift
- Tests/StytchCoreTests/UserManagementTestCase.swift
Artifacts from iOS walkthrough w/ @jhaven-stytch and @susie-stytch
Completes SDK-974
> [WIP] Add metadata updates to user management

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.13.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.14.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.15.0

- Sources/StytchCore/StytchClient/OAuth/OAuth+ThirdParty.swift
- Sources/StytchCore/StytchClient/OAuth/StytchClient+OAuth.swift
- StytchDemo/Client/Shared/OAuthAuthenticationView.swift
- Tests/StytchCoreTests/OAuthTestCase.swift
Based on https://github.com/stytchauth/stytch-ios/pull/131/files
> [AUTH-1481] Add Yahoo OAuth

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
- Sources/StytchCore/SessionStorage.swift
> [version] Increment to 0.16.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.17.0

- Sources/StytchCore/NetworkingClient/NetworkingClient+Live.swift
- Sources/StytchCore/NetworkingClient/NetworkingClient.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Bootstrap.swift
- Sources/StytchCore/StytchClient/Bootstrap/StytchClient+Bootstrap.swift
- Sources/StytchCore/StytchClientCommon/Models/BootstrapResponse.swift
- Tests/StytchCoreTests/NetworkingClientInterceptor.swift
- Tests/StytchCoreTests/NetworkingClientTestCase.swift
Linear Ticket: [SDK-1179](https://linear.app/stytch/issue/SDK-1179)
Updates the DPF logic to use the two fields
> DFP: SDK-1179 update DFP logic

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.19.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.20.0

- Sources/StytchCore/PasskeysClient/PasskeysClient+Live.swift
- Sources/StytchCore/PasskeysClient/PasskeysClient.swift
- Sources/StytchCore/StytchClient/Passkeys/PasskeysRoute.swift
- Sources/StytchCore/StytchClient/Passkeys/StytchClient+Passkeys.swift
- Sources/StytchCore/StytchClientCommon/Models/StytchError.swift
- StytchDemo/Client/Shared/PasskeysAuthenticationView.swift
- StytchDemo/Client/Shared/StytchConfiguration.plist
- StytchDemo/Client/iOS/iOS.entitlements
- StytchDemo/StytchDemo.xcodeproj/xcshareddata/xcschemes/StytchDemo (iOS).xcscheme
- Tests/StytchCoreTests/PasskeysTestCase.swift
Linear Ticket: [SDK-1200](https://linear.app/stytch/issue/SDK-1200)
1. Updates params
2. Adds isSupported and checks
3. Adds /primary and /secondary endpoints and logic
- No tests, to be added later
> SDK-1200 - Updates to Passkeys

- Sources/StytchCore/Generated/StytchClient.Passkeys.update+AsyncVariants.generated.swift
- Sources/StytchCore/StytchClient/Passkeys/PasskeysRoute.swift
- Sources/StytchCore/StytchClient/Passkeys/StytchClient+Passkeys.swift
- StytchDemo/Client/Shared/AuthenticationOptionsView.swift
- Tests/StytchCoreTests/PasskeysTestCase.swift
Linear Ticket: None
1. Adds update method
2. Uses real stytch username instead of empty string
-
> Passkeys: Add update method; Use real username instead of random string

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.21.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.22.0

- Sources/StytchCore/AppleOAuthClient/AppleOAuthClient+Live.swift
- Sources/StytchCore/CryptoClient/CryptoClient+Live.swift
- Sources/StytchCore/Extensions/Codable+Stytch.swift
- Sources/StytchCore/NetworkingClient/NetworkingClient+Live.swift
- Sources/StytchCore/NetworkingClient/NetworkingClient.swift
- Sources/StytchCore/PasskeysClient/PasskeysClient+Live.swift
- Sources/StytchCore/PollingClient/PollingClient.swift
- Sources/StytchCore/Routing/NetworkingRouter.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Bootstrap.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+DFP.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+MagicLinks.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Passwords.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SSO.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Sources/StytchCore/StytchClient/Bootstrap/StytchClient+Bootstrap.swift
- Sources/StytchCore/StytchClient/DFP/StytchClient+DFP.swift
- Sources/StytchCore/StytchClient/MagicLinks/StytchClient+MagicLinks.swift
- Sources/StytchCore/StytchClient/OAuth/OAuth+ThirdParty.swift
- Sources/StytchCore/StytchClient/OAuth/StytchClient+OAuth.swift
- Sources/StytchCore/StytchClient/Passkeys/StytchClient+Passkeys.swift
- Sources/StytchCore/StytchClient/Passwords/StytchClient+Passwords.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Sources/StytchCore/StytchClientCommon/Models/StytchError.swift
- Sources/StytchCore/WebAuthenticationSessionClient/WebAuthenticationSessionClient+Live.swift
- StytchDemo/Client/Shared/StytchDemoApp.swift
- Tests/StytchCoreTests/PollingClientTestCase.swift
- Tests/StytchCoreTests/SessionsTestCase.swift
Linear Ticket: [SDK-1312](https://linear.app/stytch/issue/SDK-1312)
- Changes all the iOS errors to use the new error classes
-
> iOS error renamings

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.23.0

- Sources/StytchUI/ActionableInfoViewController.swift
- Sources/StytchUI/AuthInputViewController.swift
- Sources/StytchUI/OAuthViewController.swift
- Sources/StytchUI/OTPCodeViewController.swift
- Sources/StytchUI/PasswordViewController.swift
Linear Ticket: [SDK-1300](https://linear.app/stytch/issue/SDK-1300)
1. Adds the retry actions that were previously left blank
2. All errors are now catched using the existing `presentError` function
-
> Add error handling

- Sources/StytchUI/Extensions/CGFloat+StytchUI.swift
- Sources/StytchUI/Extensions/UIColor+StytchUI.swift
- Sources/StytchUI/StytchTheme.swift
- Sources/StytchUI/StytchUIClient.swift
Linear Ticket: [SDK-1301](https://linear.app/stytch/issue/SDK-1301)
1. Adds theming support
- I hate having to do the lint disable for force_unwrapping, but it's a fact of life, since the config is _technically_ nil-able, but in practice never will be
> SDK-1301 Support theming

- StytchDemo/StytchDemo.xcodeproj/project.pbxproj
- StytchDemo/StytchUIDemo/StytchUIDemo.entitlements
- StytchDemo/StytchUITests/StytchUITests.swift
Linear Ticket: [SDK-1363](https://linear.app/stytch/issue/SDK-1363)
1. Adds OAuth tests
-
> SDK-1363 Add OAuth tests

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.26.0

- Sources/StytchCore/StytchClientCommon/Models/StytchError.swift
- Sources/StytchUI/AuthHomeViewController.swift
- Sources/StytchUI/AuthHomeViewModel.swift
- Sources/StytchUI/AuthInputViewController.swift
- Sources/StytchUI/AuthInputViewModel.swift
- Sources/StytchUI/OTPCodeViewController.swift
- Sources/StytchUI/OTPCodeViewModel.swift
- Sources/StytchUI/Previews.swift
- Sources/StytchUI/StytchUIClient.swift
- StytchDemo/Client/Shared/AuthenticationOptionsView.swift
- StytchDemo/StytchUIDemo/StytchUIDemoApp.swift
- StytchDemo/StytchUITests/StytchUITests.swift
- Tests/StytchUIUnitTests/OTPCodeViewModelTest.swift
Linear Tickets: 
- [SDK-1420](https://linear.app/stytch/issue/SDK-1420)
- [SDK-1421](https://linear.app/stytch/issue/SDK-1421)
- Adds Email and WhatsApp OTP to the UI SDK
- Adds UI config checks
-
> iOS UI tweaks

- README.md
Linear Ticket: [SDK-1500](https://linear.app/stytch/issue/SDK-1500)
1. Adds documentation for Passkeys
-
> Add Passkeys documentation

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.27.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.28.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.29.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.31.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.32.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.33.0

- Sources/StytchCore/PollingClient/PollingClient.swift
- StytchDemo/Client/Shared/AuthenticationOptionsView.swift
Fix compile error in sample app missed in the previous pr. 
https://github.com/stytchauth/stytch-ios/pull/235
Stop and invalidate the time on the main thread.
> Fix compile error in sample app and stop and invalidate the time on the main thread.

- Sources/StytchCore/Extensions/Error+StytchAPIError.swift
Add convenience extension for logging errors.
> Add error logging extension

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.36.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.37.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.38.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.39.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.40.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.41.0

- Package.swift
- Sources/StytchUI/ViewControllers/AuthInputViewController.swift
- Stytch/Stytch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Closes #278 
1. Updates PhoneNumberKit version to latest
2. Updates our implementation to account for new options parameter
> Update phone number kit to address compilation issue in XCode beta

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.42.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.43.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.44.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.45.0

- Sources/StytchCore/Generated/StytchB2BClient.SCIM.createConnection+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.SCIM.deleteConnection+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.SCIM.getConnection+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.SCIM.getConnectionGroups+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.SCIM.rotateCancel+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.SCIM.rotateComplete+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.SCIM.rotateStart+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchB2BClient.SCIM.updateConnection+AsyncVariants.generated.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Routes.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SCIM/StytchB2BClient+SCIM+Parameters.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SCIM/StytchB2BClient+SCIM+Responses.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+SCIM/StytchB2BClient+SCIM.swift
- Stytch/DemoApps/B2BWorkbench/ViewControllers/AuthHomeViewController.swift
- Stytch/DemoApps/B2BWorkbench/ViewControllers/AuthMethodControllers/SCIMViewController.swift
- Stytch/DemoApps/B2BWorkbench/ViewControllers/RootViewController.swift
- Stytch/Stytch.xcodeproj/project.pbxproj
- Tests/StytchCoreTests/B2BSCIMTestCase.swift
[SDK-2023 - [iOS] Add SCIM Endpoints to iOS SDK](https://linear.app/stytch/issue/SDK-2023/[ios]-add-scim-endpoints-to-ios-sdk)
> [SDK-2023] Add SCIM Endpoints to iOS SDK

- Sources/StytchCore/Documentation.docc/StytchCore.md
https://linear.app/stytch/issue/SDK-2024/[ios]-broken-links-in-docs-homepage
- Removed link to stale tutorials
- Add link to StytchUI Docs
- Trying to fix broken links in the main landing page readme file
> Trying to fix broken links

- .github/workflows/docs.yml
Fix depdabot's mixed match dependency error.
> Update upload / download artifact versions

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.46.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.47.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.48.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.49.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.50.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.51.0

- Sources/StytchCore/StytchB2BClient/Models/B2BMFAAuthenticateResponse.swift
1. Modify visibility of allowedAuthMethods in PrimaryRequired
> Modify visibility of allowedAuthMethods in PrimaryRequired

- Sources/StytchCore/SharedModels/Response.swift
- Sources/StytchCore/StytchB2BClient/Models/B2BMFAAuthenticateResponse.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Common.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OAuth/StytchB2BClient+OAuth.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+OTP/StytchB2BClient+OTP+Email.swift
- Stytch/DemoApps/B2BWorkbench/ViewControllers/AuthMethodControllers/OrganizationViewController.swift
- Tests/StytchCoreTests/B2BDiscoveryTestCase.swift
> Add missing fields to discovered organization

- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Common.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/B2BAuthenticationManager.swift
- Sources/StytchUI/StytchB2BUIClient/StytchB2BUIClient/StytchB2BUIClient+ValidProducts.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BAuthHomeViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BOAuthViewController/B2BOAuthViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BSSOViewController/B2BSSOViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BSSOViewController/B2BSSOViewModel.swift
- Stytch/DemoApps/StytchB2BUIDemo/StytchB2BUIDemoApp.swift
[[iOS] Build MainScreen](https://linear.app/stytch/issue/SDK-2278/[ios]-build-mainscreen)
1. Add SSO to the home screen
> [B2B UI] Add SSO to the home screen

- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Sources/StytchCore/StytchClientType.swift
Linear Ticket: [LINEAR_NUMBER](https://linear.app/stytch/issue/YOUR_TICKET)
1.
> Add missing dfppaDomain parameter to configure call

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.52.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.53.0

- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Common.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient+Passwords.swift
- Sources/StytchUI/StytchB2BUIClient/Shared/BaseViewController+MFA.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordResetViewController/PasswordResetViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/PasswordResetViewController/PasswordResetViewModel.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/SMSOTPEnrollmentViewController/SMSOTPEnrollmentViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/SMSOTPEntryViewController/SMSOTPEntryViewController.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/SMSOTPEntryViewController/SMSOTPEntryViewModel.swift
- Sources/StytchUI/StytchUIClient/StytchUIClient+Configuration.swift
- Sources/StytchUI/StytchUIClient/StytchUIClient.swift
- Tests/StytchCoreTests/B2BPasswordsTestCase.swift
1. Add dfppa domain to consumer UI config.
2. Add check for siding sms otp on entry screen.
3. Add logic for password strength check.
> [B2B UI] Bugbashing 2

- Stytch/DemoApps/B2BWorkbench/ViewControllers/AuthHomeViewController.swift
- Stytch/DemoApps/B2BWorkbench/ViewControllers/AuthMethodControllers/B2BUIViewController.swift
- Stytch/DemoApps/StytchB2BUIDemo/Info.plist
- Stytch/DemoApps/StytchUIDemo/Info.plist
- Stytch/Stytch.xcodeproj/project.pbxproj
- tutorials/B2B-UI.md
- tutorials/NavigatingTheProject.md
- tutorials/UI.md
1. Update Readmes and Sample Apps for StytchUI - 2
> Update Readmes and Sample Apps for StytchUI - 2

- Stytch/DemoApps/B2BWorkbench/ViewControllers/AuthMethodControllers/B2BUIViewController.swift
- tutorials/B2B-UI.md
- tutorials/NavigatingTheProject.md
- tutorials/UI.md
1. Update Readmes and Sample Apps for StytchUI - 3
> Update Readmes and Sample Apps for StytchUI - 3

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.54.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.56.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.57.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.58.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.59.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.61.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.62.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.63.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.64.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.65.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.66.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.68.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.69.0

- Stytch/DemoApps/StytchB2BUIDemo/ContentView.swift
- Stytch/DemoApps/StytchUIDemo/ContentView.swift
This PR adds some helpful code in the pre built UI sample apps to copy and paste around listening to all the possible public facing publishers in the SDK.
> Add more sample code to the prebuilt UI demo apps

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.70.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.71.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.72.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.73.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.74.0

- Sources/StytchCore/Documentation.docc/Tutorials/stytch/basics/getting-started/add-eml.tutorial
- Sources/StytchCore/Generated/StytchB2BClient.handle+AsyncVariants.generated.swift
- Sources/StytchCore/Generated/StytchClient.handle+AsyncVariants.generated.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/Biometrics/StytchClient+Biometrics.swift
- Sources/StytchCore/StytchClient/OAuth/OAuth+Apple.swift
- Sources/StytchCore/StytchClient/Passkeys/StytchClient+Passkeys.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Sources/StytchCore/StytchClient/TOTP/StytchClient+TOTP.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/OAuthViewController/OAuthViewModel.swift
- tutorials/Deeplinks.md
- tutorials/EmailMagicLinks.md
- tutorials/Passwords.md
- tutorials/Sessions.md
Catch remaining instances of `sessionDuration` and make them `sessionDurationMinutes`.
Continuation of: https://github.com/stytchauth/stytch-ios/pull/436
> sessionDuration -> sessionDurationMinutes

- Sources/StytchCore/ClientType.swift
- Sources/StytchCore/SharedModels/BootstrapResponse.swift
- Sources/StytchCore/StartupClient.swift
- Sources/StytchCore/StytchClientType.swift
- Tests/StytchCoreTests/B2BRBACTestCase.swift
[[iOS] Add "vertical" field to bootstrap response object.](https://linear.app/stytch/issue/SDK-2612/[ios]-add-vertical-field-to-bootstrap-response-object)
> Add vertical to bootstrap response

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.75.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.76.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.77.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.78.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.81.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.86.0

- Sources/StytchCore/SharedModels/BootstrapResponse.swift
- Sources/StytchCore/StytchB2BClient/StytchB2BClient.swift
- Sources/StytchCore/StytchClient/StytchClient.swift
- Sources/StytchUI/StytchB2BUIClient/ViewControllers/B2BAuthHomeViewController/B2BAuthHomeViewModel.swift
- Sources/StytchUI/StytchUIClient/ViewControllers/AuthHomeViewController/AuthHomeViewModel.swift
Linear Ticket: [SDK-2826](https://linear.app/stytch/issue/SDK-2826)
1.
> SDK-2826 Start logging bootstrap data along with ui config for both B2C and B2B UI

- Sources/StytchCore/SharedModels/DeviceHistory.swift
- Sources/StytchCore/StytchB2BClient/Models/B2BAuthenticateResponse.swift
- Sources/StytchCore/StytchB2BClient/Models/B2BMFAAuthenticateResponse.swift
- Sources/StytchCore/StytchClient/Models/AuthenticateResponse.swift
Continuation of https://github.com/stytchauth/stytch-ios/pull/527 based on some feedback missed.
> Fixes for device history usage and comments

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.88.0

- Sources/StytchCore/ClientInfo/ClientInfo+Version.swift
> [version] Increment to 0.89.0

- Sources/StytchCore/SharedModels/ClientInfo+Version.swift
> [version] Increment to 0.92.0
